const { createChapter } = require('./helper');

function getClass9Subjects() {
  const mathChapters = [
    createChapter('c9-math-ch1', 1, 'Number Systems', 'Rational and irrational numbers, real numbers and decimal expansions, operations on real numbers, laws of exponents.', 'iemh1', 1, 24, 30, 'completed', 100,
      ['Terminating and non-terminating recurring decimals are rational', 'Representation of √x on the number line using geometry', 'Rationalising the denominator containing square roots', 'Laws of exponents: aᵖ · aᑫ = aᵖ⁺ᑫ, (aᵖ)ᑫ = aᵖᑫ'],
      [{t: 'Irrational Proof', d: 'Numbers whose decimal expansion is non-terminating non-recurring (√2, π)'}, {t: 'Rationalisation', d: 'Multiply numerator and denominator by conjugate surd (√a - √b)'}],
      'Every real number is represented by a unique point on the number line.',
      {q: 'Rationalise the denominator of 1 / (7 + 3√2).', a: 'Multiply by (7 - 3√2): (7 - 3√2) / (49 - 18) = (7 - 3√2) / 31.'},
      'Assuming π = 22/7; 22/7 is only a rational approximation of the irrational number π.'),
    createChapter('c9-math-ch2', 2, 'Polynomials', 'Polynomials in one variable, zeroes of a polynomial, Remainder Theorem, Factor Theorem, algebraic identities.', 'iemh1', 2, 26, 32, 'completed', 100,
      ['Degree of polynomial and classification: linear, quadratic, cubic', 'Factor Theorem: (x - a) is a factor of p(x) if p(a) = 0', 'Identities: (x + y + z)², (x ± y)³, x³ + y³ + z³ - 3xyz'],
      [{t: 'Factor Theorem', d: 'If p(a) = 0, then (x - a) is a factor of p(x)'}, {t: 'Conditional Identity', d: 'If x + y + z = 0, then x³ + y³ + z³ = 3xyz'}],
      'If x + y + z = 0, always directly use x³ + y³ + z³ = 3xyz to save calculation time.',
      {q: 'Evaluate (-12)³ + (7)³ + (5)³ without actual cubing.', a: 'Here (-12) + 7 + 5 = 0. Therefore, (-12)³ + 7³ + 5³ = 3(-12)(7)(5) = -1260.'},
      'Taking negative numbers or fractions as exponents in polynomials; exponents must be non-negative integers.'),
    createChapter('c9-math-ch3', 3, 'Coordinate Geometry', 'Cartesian plane, coordinate axes (x-axis, y-axis), quadrants, coordinates of a point (abscissa and ordinate).', 'iemh1', 3, 14, 20, 'completed', 100,
      ['Cartesian coordinate axes: XOX\' and YOY\' intersecting at origin (0, 0)', 'Four quadrants: Q1 (+, +), Q2 (-, +), Q3 (-, -), Q4 (+, -)', 'Abscissa is x-coordinate, Ordinate is y-coordinate'],
      [{t: 'Abscissa', d: 'Perpendicular distance of a point from the y-axis (x-coordinate)'}, {t: 'Ordinate', d: 'Perpendicular distance of a point from the x-axis (y-coordinate)'}],
      'Point on x-axis has coordinates (x, 0); point on y-axis has coordinates (0, y).',
      {q: 'Write the coordinates of the point whose abscissa is -3 and which lies on the x-axis.', a: 'Coordinates are (-3, 0).'},
      'Confusing abscissa (x) with ordinate (y).'),
    createChapter('c9-math-ch4', 4, 'Linear Equations in Two Variables', 'Standard form ax + by + c = 0, solutions of linear equations (infinitely many), graph of linear equation in two variables.', 'iemh1', 4, 16, 22, 'completed', 100,
      ['Linear equation in two variables has infinitely many solutions', 'Standard form: ax + by + c = 0 where a, b ≠ 0', 'Graph is always a straight line on the Cartesian plane'],
      [{t: 'General Form', d: 'ax + by + c = 0'}, {t: 'Equation of x-axis', d: 'y = 0'}, {t: 'Equation of y-axis', d: 'x = 0'}],
      'Every point on the line satisfies the equation, and every solution represents a point on the line.',
      {q: 'Find the value of k if x = 2, y = 1 is a solution of the equation 2x + 3y = k.', a: 'Substitute x = 2, y = 1: 2(2) + 3(1) = 4 + 3 = 7. Thus k = 7.'},
      'Plotting only two points; always plot at least 3 points to detect arithmetic errors.'),
    createChapter('c9-math-ch5', 5, 'Introduction to Euclid\'s Geometry', 'Euclid’s definitions, axioms and postulates (Postulates 1 to 5), equivalent versions of Euclid’s fifth postulate (Playfair\'s axiom).', 'iemh1', 5, 12, 18, 'not_started', 0,
      ['Definitions of point, line, and surface', 'Axioms: assumptions valid throughout mathematics without proof', 'Euclid’s 5 Postulates, especially Postulate 5 (parallel lines postulate)'],
      [{t: 'Axiom 1', d: 'Things which are equal to the same thing are equal to one another'}, {t: 'Postulate 5', d: 'If two lines intersect third line and interior angles sum < 180°, lines meet on that side'}],
      'Euclid’s fifth postulate guarantees the existence and uniqueness of parallel lines.',
      {q: 'State Euclid\'s fourth axiom.', a: 'Things which coincide with one another are equal to one another.'},
      'Confusing axioms (applicable across all mathematics) with postulates (specific to geometry).'),
    createChapter('c9-math-ch6', 6, 'Lines and Angles', 'Basic terms and definitions, intersecting lines and non-intersecting lines, pairs of angles (linear pair, vertically opposite), parallel lines and transversal, angle sum property of a triangle.', 'iemh1', 6, 20, 26, 'not_started', 0,
      ['Linear Pair Axiom: adjacent angles on straight line sum to 180°', 'Vertically opposite angles are equal', 'Transversal: corresponding angles equal, alternate interior angles equal, co-interior angles sum to 180°', 'Angle sum of triangle = 180°; exterior angle = sum of two opposite interior angles'],
      [{t: 'Linear Pair', d: '∠1 + ∠2 = 180° for adjacent angles on a straight line'}, {t: 'Exterior Angle Theorem', d: 'Exterior angle of a triangle equals sum of two opposite interior angles'}],
      'Identify parallel lines and transversal before applying alternate or corresponding angle theorems.',
      {q: 'In a triangle, if angles are in the ratio 2 : 3 : 4, find all angles.', a: '2x + 3x + 4x = 180° ⇒ 9x = 180° ⇒ x = 20°. Angles: 40°, 60°, 80°.'},
      'Assuming lines are parallel without explicit statement or proof in question.'),
    createChapter('c9-math-ch7', 7, 'Triangles', 'Congruence of triangles, criteria for congruence (SAS, ASA, AAS, SSS, RHS), properties of isosceles triangles, inequalities in a triangle.', 'iemh1', 7, 24, 32, 'not_started', 0,
      ['Two figures are congruent if they have identical shape and size', 'Criteria: SAS, ASA, AAS, SSS, RHS (ASS and AAA are NOT valid criteria!)', 'Angles opposite to equal sides of a triangle are equal (CPCTC)'],
      [{t: 'CPCTC', d: 'Corresponding Parts of Congruent Triangles are Congruent'}, {t: 'RHS Criterion', d: 'Right angle, Hypotenuse, and one Side equal in two right triangles'}],
      'AAA and ASS are NOT congruence criteria! Memorise SAS, ASA, AAS, SSS, RHS only.',
      {q: '△ABC is an isosceles triangle with AB = AC. Prove that ∠B = ∠C.', a: 'Draw AD ⊥ BC. In △ABD and △ACD: AB = AC (given), AD = AD (common), ∠ADB = ∠ADC = 90°. By RHS, △ABD ≅ △ACD ⇒ ∠B = ∠C by CPCTC.'},
      'Applying AAA to prove triangles congruent (AAA proves similarity, not congruence).'),
    createChapter('c9-math-ch8', 8, 'Quadrilaterals', 'Angle sum property of a quadrilateral (360°), properties of a parallelogram, conditions for a quadrilateral to be a parallelogram, Mid-point Theorem and its converse.', 'iemh1', 8, 22, 28, 'not_started', 0,
      ['Sum of angles of a quadrilateral is 360°', 'Diagonal of a parallelogram divides it into two congruent triangles', 'Opposite sides and opposite angles of a parallelogram are equal; diagonals bisect each other', 'Mid-point Theorem: line joining midpoints of two sides of triangle is parallel to third side and half of it'],
      [{t: 'Mid-point Theorem', d: 'In △ABC, if D and E are midpoints of AB and AC, then DE || BC and DE = 1/2 BC'}, {t: 'Parallelogram Diagonal', d: 'A diagonal divides parallelogram into two congruent triangles'}],
      'Mid-point Theorem is a favorite 4-mark theorem in Class 9 annual examinations.',
      {q: 'The angles of a quadrilateral are in the ratio 3 : 5 : 9 : 13. Find all the angles.', a: 'Sum = 30x = 360° ⇒ x = 12°. Angles are 36°, 60°, 108°, 156°.'},
      'Assuming a quadrilateral is a parallelogram without proving opposite sides are equal or parallel.'),
    createChapter('c9-math-ch9', 9, 'Circles', 'Circles and related terms (radius, chord, sector, segment), perpendicular from centre to chord bisects the chord, equal chords and their distances from centre, angle subtended by an arc at centre is double the angle at remaining circumference, cyclic quadrilaterals (opposite angles sum to 180°).', 'iemh1', 9, 24, 30, 'not_started', 0,
      ['Perpendicular from centre of a circle to a chord bisects the chord', 'Angle subtended by an arc at centre is twice the angle subtended by it at any point on the remaining part of circle', 'Angles in the same segment of a circle are equal; angle in a semicircle is a right angle (90°)', 'Sum of either pair of opposite angles of a cyclic quadrilateral is 180°'],
      [{t: 'Arc-Centre Theorem', d: '∠AOB = 2 ∠APB for any point P on circle'}, {t: 'Semicircle Angle', d: 'Angle inscribed in a semicircle is 90°'}, {t: 'Cyclic Quadrilateral', d: '∠A + ∠C = 180° and ∠B + ∠D = 180°'}],
      'Angle subtended by diameter at circumference is ALWAYS 90° (right angle).',
      {q: 'In a circle, an arc subtends an angle of 110° at the centre. Find the angle it subtends on the remaining circumference.', a: 'Angle on circumference = 110° / 2 = 55°.'},
      'Taking angle at circumference as double the angle at centre (it is half of centre angle).'),
    createChapter('c9-math-ch10', 10, 'Heron\'s Formula', 'Area of a triangle using Heron’s formula: √[s(s - a)(s - b)(s - c)] where semi-perimeter s = (a + b + c)/2, applications in finding area of scalene and isosceles triangles.', 'iemh1', 10, 16, 22, 'not_started', 0,
      ['Semi-perimeter: s = (a + b + c) / 2', 'Heron\'s Area Formula: A = √[s(s - a)(s - b)(s - c)]', 'Useful for triangles where height is not known directly'],
      [{t: 'Semi-perimeter', d: 's = (a + b + c) / 2'}, {t: 'Heron\'s Formula', d: 'Area = √[s(s - a)(s - b)(s - c)]'}],
      'Calculate s first, then (s - a), (s - b), and (s - c) separately to avoid arithmetic mistakes under the radical.',
      {q: 'Find the area of a triangle whose sides are 13 cm, 14 cm, and 15 cm.', a: 's = (13+14+15)/2 = 21 cm. Area = √[21 × 8 × 7 × 6] = √[7056] = 84 cm².'},
      'Forgetting to divide perimeter by 2 to get semi-perimeter s.'),
    createChapter('c9-math-ch11', 11, 'Surface Areas and Volumes', 'Surface areas and volumes of right circular cones and spheres (including hemispheres).', 'iemh1', 11, 22, 30, 'not_started', 0,
      ['Curved surface area of cone: πrl, Total surface area: πr(l + r), where l = √(r² + h²)', 'Surface area of sphere: 4πr²', 'Hemisphere: CSA = 2πr², TSA = 3πr²', 'Volumes: Cone = (1/3)πr²h, Sphere = (4/3)πr³, Hemisphere = (2/3)πr³'],
      [{t: 'Cone CSA', d: 'πrl where l = √(r² + h²)'}, {t: 'Sphere Volume', d: '(4/3)πr³'}, {t: 'Hemisphere TSA', d: '3πr²'}],
      'In rationalised 2026 syllabus, Cubes and Cylinders are reviewed from Class 8; focus on Cones, Spheres, and Hemispheres.',
      {q: 'Find the total surface area of a hemisphere of radius 10 cm (use π = 3.14).', a: 'TSA = 3πr² = 3 × 3.14 × (10)² = 3 × 314 = 942 cm².'},
      'Using 2πr² for TSA of solid hemisphere; solid hemisphere has curved surface plus flat circular base (3πr²).'),
    createChapter('c9-math-ch12', 12, 'Statistics', 'Graphical representation of data: Bar graphs, Histograms (with uniform width and varying widths), Frequency polygons.', 'iemh1', 12, 18, 25, 'not_started', 0,
      ['Bar graphs: uniform width bars with equal spacing', 'Histograms: continuous frequency distributions with adjacent rectangles (area proportional to frequency)', 'Adjusted frequency calculation for histograms with unequal class widths', 'Frequency polygons: plotted using class marks (upper limit + lower limit)/2'],
      [{t: 'Class Mark', d: '(Upper class limit + Lower class limit) / 2'}, {t: 'Adjusted Frequency', d: '(Minimum class size / Class size) × Frequency'}],
      'For frequency polygons, always join to the midpoints of hypothetical classes at both ends with frequency 0.',
      {q: 'Find the class mark of the class interval 150 - 160.', a: 'Class mark = (150 + 160) / 2 = 310 / 2 = 155.'},
      'Plotting frequency polygon against class boundaries instead of class marks.')
  ];

  const scienceChapters = [
    createChapter('c9-sci-ch1', 1, 'Matter in Our Surroundings', 'Physical nature of matter, characteristics of particles, states of matter (solid, liquid, gas), change of state (melting, boiling, sublimation, latent heat), evaporation and factors affecting it, cooling effect.', 'iesc1', 1, 16, 22, 'completed', 100,
      ['Particle characteristics: continuous motion, intermolecular spaces, forces of attraction', 'Latent heat of fusion and latent heat of vaporisation', 'Sublimation (solid directly to gas, e.g. Camphor, Ammonium chloride)', 'Factors affecting evaporation: surface area, temperature, humidity, wind speed'],
      [{t: 'Latent Heat of Vaporisation', d: 'Heat energy required to change 1 kg of liquid to gas at atmospheric pressure at its boiling point'}, {t: 'Evaporation Cooling', d: 'Particles absorb latent heat from surroundings during evaporation, causing cooling'}],
      'Steam causes more severe burns than boiling water at 100°C because steam contains extra latent heat of vaporisation.',
      {q: 'Why do we wear cotton clothes in summer?', a: 'Cotton is a good absorber of water; it absorbs sweat and exposes it to atmosphere, facilitating evaporation which causes cooling.'},
      'Confusing boiling (bulk phenomenon) with evaporation (surface phenomenon occurring below boiling point).'),
    createChapter('c9-sci-ch2', 2, 'Is Matter Around Us Pure?', 'Mixtures (homogeneous vs heterogeneous), Solutions (solvent, solute, concentration mass percentage), Suspensions and Colloids (Tyndall effect, Brownian motion), Physical vs Chemical changes.', 'iesc1', 2, 20, 26, 'completed', 100,
      ['True solution (<1 nm) vs Colloid (1-1000 nm) vs Suspension (>1000 nm)', 'Tyndall effect: scattering of light beam by colloidal particles', 'Dispersed phase and dispersion medium in colloids (Sol, Gel, Emulsion, Aerosol)', 'Concentration of solution = (Mass of solute / Mass of solution) × 100'],
      [{t: 'Tyndall Effect', d: 'Scattering of visible light by colloidal particles making beam path visible'}, {t: 'Mass % Concentration', d: '[Mass of Solute / (Mass of Solute + Mass of Solvent)] × 100'}],
      'Remember that true solutions do NOT show Tyndall effect; only colloids and fine suspensions show Tyndall effect.',
      {q: 'A solution contains 40 g of common salt in 320 g of water. Calculate concentration in mass percentage.', a: 'Mass of solution = 40 + 320 = 360 g. Concentration = (40 / 360) × 100 = 11.1%.'},
      'Dividing by mass of solvent instead of mass of entire solution in concentration formula.'),
    createChapter('c9-sci-ch3', 3, 'Atoms and Molecules', 'Laws of chemical combination (Law of Conservation of Mass, Law of Constant Proportions), Dalton’s atomic theory, Atoms, atomic mass unit (u), Molecules, Chemical formula writing, Molecular mass and formula unit mass.', 'iesc1', 3, 22, 28, 'completed', 100,
      ['Law of conservation of mass (Lavoisier) and constant proportions (Proust)', 'Dalton’s atomic theory postulates and limitations', 'Writing formulas using criss-cross method of valencies', 'Molecular mass = sum of atomic masses of all constituent atoms in molecule'],
      [{t: 'Law of Constant Proportions', d: 'In a chemical substance elements are always present in definite proportions by mass (e.g. H2O is 1:8)'}, {t: 'Atomic Mass Unit (u)', d: 'Mass equal to exactly 1/12th the mass of one carbon-12 atom'}],
      'Practise writing formulas using criss-cross method (e.g. Al³⁺ and O²⁻ gives Al2O3).',
      {q: 'Calculate the molecular mass of nitric acid, HNO3 (H=1, N=14, O=16).', a: 'Molecular mass = 1 + 14 + 3(16) = 15 + 48 = 63 u.'},
      'Confusing formula unit mass (for ionic compounds like NaCl) with molecular mass.'),
    createChapter('c9-sci-ch4', 4, 'Structure of the Atom', 'Sub-atomic particles (electrons, protons, neutrons), Thomson’s model, Rutherford’s alpha-particle scattering experiment and nuclear model, Bohr’s model of atom, Electronic configuration (Bohr-Bury scheme), Valency, Atomic number (Z), Mass number (A), Isotopes and Isobars.', 'iesc1', 4, 20, 26, 'not_started', 0,
      ['Rutherford scattering: most alpha particles passed straight, few deflected, 1 in 12,000 rebounded', 'Bohr\'s orbits: discrete energy shells K, L, M, N (maximum 2n² electrons)', 'Valency: combining capacity of an atom (electrons gained, lost, or shared)', 'Isotopes: same atomic number, different mass number (¹²C, ¹⁴C); Isobars: same mass number, different atomic number (⁴⁰Ar, ⁴⁰Ca)'],
      [{t: 'Bohr-Bury Rule', d: 'Maximum electrons in shell n is 2n²; outermost shell cannot hold more than 8 electrons'}, {t: 'Isotopes', d: 'Atoms of same element with same atomic number Z but different mass number A'}],
      'Isotopes share identical chemical properties because they have the same number of valence electrons.',
      {q: 'Describe the two main conclusions drawn from Rutherford\'s alpha-particle scattering experiment.', a: '1. Most of the inside of the atom is empty space. 2. Positive charge and almost all mass is concentrated in a tiny dense region called the nucleus.'},
      'Confusing isotopes (same Z, different A) with isobars (different Z, same A).'),
    createChapter('c9-sci-ch5', 5, 'The Fundamental Unit of Life', 'Cell discovery (Robert Hooke, Leeuwenhoek), Cell theory (Schleiden, Schwann, Virchow), Plasma membrane (diffusion and osmosis: hypotonic, isotonic, hypertonic), Cell wall (plasmolysis), Nucleus (chromosomes, DNA), Cytoplasm and Organelles (ER, Golgi apparatus, Lysosomes, Mitochondria, Plastids, Vacuoles).', 'iesc1', 5, 24, 30, 'not_started', 0,
      ['Plasma membrane is selectively permeable, made of lipids and proteins', 'Osmosis: movement of water across semi-permeable membrane from high to low water potential', 'Mitochondria = Powerhouse of cell (synthesises ATP); Lysosomes = Suicide bags (hydrolytic enzymes)', 'Plant cell has cell wall, plastids, large central vacuole; animal cell does not'],
      [{t: 'Powerhouse of Cell', d: 'Mitochondria (produces cellular energy currency ATP)'}, {t: 'Suicide Bags', d: 'Lysosomes (contain powerful digestive enzymes capable of digesting own cell)'}],
      'Draw and label plant cell vs animal cell diagrams cleanly with all organelles.',
      {q: 'What will happen if a plant cell is placed in a hypertonic solution?', a: 'Water moves out of the cell via exosmosis, causing shrinkage of the protoplasm away from the cell wall (plasmolysis).'},
      'Calling ribosome the powerhouse; ribosome is the site of protein synthesis.'),
    createChapter('c9-sci-ch6', 6, 'Tissues', 'Plant tissues: Meristematic (apical, intercalary, lateral/cambium) vs Permanent (Simple: parenchyma, collenchyma, sclerenchyma; Complex: xylem and phloem). Animal tissues: Epithelial, Connective (blood, bone, cartilage, ligament, tendon, areolar, adipose), Muscular (striated, smooth, cardiac), Nervous tissue (neuron).', 'iesc1', 6, 26, 32, 'not_started', 0,
      ['Apical meristem increases length; Lateral meristem (cambium) increases girth', 'Simple permanent: Parenchyma (storage/photosynthesis), Collenchyma (flexibility), Sclerenchyma (hardness, lignin)', 'Complex vascular: Xylem (unidirectional transport of water/minerals, tracheids, vessels), Phloem (bidirectional translocation of food, sieve tubes, companion cells)', 'Tendon joins muscle to bone; Ligament joins bone to bone'],
      [{t: 'Xylem vs Phloem', d: 'Xylem transports water/minerals unidirectionally; Phloem translocates food bidirectionally'}, {t: 'Tendon vs Ligament', d: 'Tendon = muscle to bone; Ligament = bone to bone'}],
      'Mnemonic: Ligament = Bone-to-Bone (BLB); Tendon = Muscle-to-Bone (MTB).',
      {q: 'Differentiate between voluntary (striated) and involuntary (smooth) muscle tissues.', a: 'Striated muscles are cylindrical, multinucleated, have alternate light/dark bands, and are under conscious control. Smooth muscles are spindle-shaped, uninucleated, unstriated, and involuntary.'},
      'Confusing tendons and ligaments in connective tissue identification questions.'),
    createChapter('c9-sci-ch7', 7, 'Motion', 'Describing motion, distance vs displacement, speed and velocity, uniform and non-uniform motion, acceleration, graphical representation (distance-time and velocity-time graphs), Equations of motion: v = u + at, s = ut + 1/2 at², v² = u² + 2as, Uniform circular motion.', 'iesc1', 7, 26, 35, 'not_started', 0,
      ['Distance is scalar (path length); Displacement is vector (shortest straight distance between initial and final position)', 'Acceleration a = (v - u) / t', 'Area under velocity-time graph gives displacement; slope gives acceleration', 'Three equations of motion: v = u + at, s = ut + 1/2 at², v² - u² = 2as'],
      [{t: 'First Equation', d: 'v = u + at'}, {t: 'Second Equation', d: 's = ut + (1/2)at²'}, {t: 'Third Equation', d: 'v² = u² + 2as'}, {t: 'Circular Speed', d: 'v = 2πr / t (accelerated motion due to continuous direction change)'}],
      'In uniform circular motion, speed is constant but velocity is continuously changing because direction changes at every instant.',
      {q: 'A train starting from rest attains a velocity of 72 km/h in 5 minutes. Assuming uniform acceleration, find acceleration and distance travelled.', a: 'u = 0, v = 72 km/h = 20 m/s, t = 300 s. a = (20 - 0)/300 = 1/15 m/s². s = ut + 1/2 at² = 0 + 1/2(1/15)(300)² = 3000 m = 3 km.'},
      'Forgetting to convert km/h to m/s (multiply by 5/18) and minutes to seconds.'),
    createChapter('c9-sci-ch8', 8, 'Force and Laws of Motion', 'Balanced and unbalanced forces, First law of motion (Inertia and mass), Second law of motion (Momentum p = mv, F = ma), Third law of motion (Action and reaction are equal and opposite acting on different bodies), Conservation of momentum.', 'iesc1', 8, 24, 30, 'not_started', 0,
      ['First Law / Law of Inertia: body remains at rest or in uniform motion unless acted upon by external net force', 'Mass is the quantitative measure of inertia of an object', 'Second Law: Rate of change of momentum is proportional to applied force (F = ma)', 'Third Law: To every action there is an equal and opposite reaction acting on different bodies'],
      [{t: 'Newton\'s Second Law', d: 'F = dp/dt = m(v - u)/t = ma (Unit: Newton, 1 N = 1 kg·m/s²)'}, {t: 'Conservation of Momentum', d: 'm1u1 + m2u2 = m1v1 + m2v2 (in isolated system without external force)'}],
      'Action and reaction never cancel each other because they act on TWO DIFFERENT bodies.',
      {q: 'Why does a fielder pull his hands backwards while catching a fast cricket ball?', a: 'By pulling hands backwards, the fielder increases the time taken to bring ball’s velocity to zero, thereby reducing rate of change of momentum and hence the impact force.'},
      'Claiming action and reaction cancel out; they act on two different interacting bodies.'),
    createChapter('c9-sci-ch9', 9, 'Gravitation', 'Universal Law of Gravitation: F = G(m1m2)/d², Free fall, acceleration due to gravity (g = 9.8 m/s²), variation of g, mass vs weight, thrust and pressure, pressure in fluids, Archimedes’ principle and relative density.', 'iesc1', 9, 22, 28, 'not_started', 0,
      ['Universal Gravitation: F = G (M·m) / R², G = 6.67 × 10⁻¹¹ N·m²/kg²', 'Acceleration due to gravity: g = GM / R² (independent of mass of falling body)', 'Mass is constant everywhere; Weight W = mg varies with local g (g on moon = 1/6 g on earth)', 'Archimedes\' Principle: upward buoyant force = weight of displaced fluid'],
      [{t: 'Universal Gravitational Constant', d: 'G = 6.673 × 10⁻¹¹ N·m²/kg²'}, {t: 'Weight on Moon', d: 'W_moon = (1/6) W_earth'}, {t: 'Archimedes\' Principle', d: 'Buoyant force F_b = V_displaced × ρ_fluid × g'}],
      'All objects drop at the same acceleration in vacuum regardless of their individual mass.',
      {q: 'Mass of an object is 10 kg. What is its weight on earth and on the moon?', a: 'W_earth = mg = 10 × 9.8 = 98 N. W_moon = 98 / 6 = 16.33 N.'},
      'Measuring weight in kilograms; mass is in kg, weight is a force measured in Newtons (N).'),
    createChapter('c9-sci-ch10', 10, 'Work and Energy', 'Scientific concept of work: W = F·s·cos θ, Positive, negative and zero work, Energy and forms (Kinetic energy Ek = 1/2 mv², Potential energy Ep = mgh), Law of conservation of energy, Power: P = W/t (Watt), Commercial unit of energy (kWh).', 'iesc1', 10, 20, 26, 'not_started', 0,
      ['Work is done only when force causes displacement in direction of force (W = F · s)', 'Kinetic energy: Ek = 1/2 mv²; Potential energy: Ep = mgh', 'Law of Conservation of Energy: total mechanical energy (Ek + Ep) remains constant during free fall', 'Power = Work done / Time taken (1 Watt = 1 Joule/second; 1 kW = 1000 W)'],
      [{t: 'Work Formula', d: 'W = F × s (1 Joule = 1 N × 1 m)'}, {t: 'Kinetic Energy', d: 'Ek = (1/2) mv²'}, {t: 'Gravitational Potential Energy', d: 'Ep = mgh'}, {t: 'Commercial Unit', d: '1 unit = 1 kWh = 3.6 × 10⁶ Joules'}],
      'Work done by centripetal force is always ZERO because force is perpendicular to displacement (cos 90° = 0).',
      {q: 'An object of mass 15 kg is moving with uniform velocity of 4 m/s. What is kinetic energy possessed by object?', a: 'Ek = 1/2 mv² = 1/2 × 15 × (4)² = 1/2 × 15 × 16 = 120 Joules.'},
      'Saying work is done when a person stands holding a heavy suitcase; displacement is 0, so work done is zero.'),
    createChapter('c9-sci-ch11', 11, 'Sound', 'Production and propagation of sound, sound needs a material medium to travel, longitudinal nature of sound waves (compressions and rarefactions), characteristics of sound wave (wavelength λ, frequency ν, amplitude, time period T, velocity v = νλ), speed of sound, reflection of sound, echo, reverberation, range of hearing (20 Hz to 20,000 Hz), ultrasound applications (SONAR).', 'iesc1', 11, 22, 28, 'not_started', 0,
      ['Sound is a mechanical longitudinal wave requiring medium (cannot travel in vacuum)', 'Wave relation: Speed v = ν · λ = λ / T', 'Echo condition: minimum distance of reflector is 17.2 m at 22°C (persistence of hearing is 0.1 s)', 'Ultrasound (>20 kHz) used in SONAR (Sound Navigation and Ranging) and medical ultrasonography'],
      [{t: 'Wave Speed Formula', d: 'v = ν × λ (Frequency × Wavelength)'}, {t: 'Echo Distance', d: 'd = (v × t) / 2 (Minimum 17.2 m in air)'}, {t: 'Audible Frequency Range', d: '20 Hz to 20,000 Hz (20 kHz)'}],
      'Sound travels fastest in solids, slower in liquids, and slowest in gases (v_solid > v_liquid > v_gas).',
      {q: 'A sound wave has frequency 2 kHz and wavelength 35 cm. How long will it take to travel 1.5 km?', a: 'ν = 2000 Hz, λ = 0.35 m. v = 2000 × 0.35 = 700 m/s. Time t = Distance / Speed = 1500 / 700 = 2.14 s.'},
      'Forgetting that sound travels to the obstacle and back in echo questions (2d = v × t).'),
    createChapter('c9-sci-ch12', 12, 'Improvement in Food Resources', 'Sustainable agriculture, crop variety improvement (hybridisation, genetic modification for high yield, disease resistance), crop production management (nutrients: macronutrients and micronutrients, manure vs fertilisers, irrigation), cropping patterns (mixed cropping, intercropping, crop rotation), crop protection management (weed, insect pests, diseases), animal husbandry (cattle farming, poultry farming, egg/broiler production, fish production: capture vs culture/composite fish farming, beekeeping/apiculture).', 'iesc1', 12, 20, 26, 'not_started', 0,
      ['16 essential plant nutrients: 6 Macronutrients (N, P, K, Ca, Mg, S) and 7 Micronutrients (Fe, Mn, B, Zn, Cu, Mo, Cl)', 'Composite fish culture using 5-6 fish species with different feeding zones (Catla = surface, Rohu = middle, Mrigal/Common carp = bottom)', 'Apiculture: Italian bee (Apis mellifera) preferred for high honey collection and gentleness', 'Intercropping (definite row patterns) vs Mixed cropping (no row pattern)'],
      [{t: 'Macronutrients', d: 'Nutrients required in large quantities: Nitrogen, Phosphorus, Potassium, Calcium, Magnesium, Sulphur'}, {t: 'Composite Fish Farming', d: 'Culturing surface, column, and bottom feeders together to utilise all food niches without competition'}],
      'Memorise the 6 macronutrients and composite fish feeding zones.',
      {q: 'What are the advantages of composite fish culture?', a: 'Both local and imported fish species are used in combinations where food habits do not compete, ensuring food available in all parts of the pond is utilised, yielding high fish production.'},
      'Confusing capture fishing (catching wild fish from natural waters) with culture fishery (farming fish in controlled water bodies).')
  ];

  const socialChapters = [
    // History
    createChapter('c9-soc-ch1', 1, 'The French Revolution', 'French society in late 18th century (Three Estates), outbreak of revolution (Storming of Bastille, 14 July 1789), constitutional monarchy, Reign of Terror (Robespierre), Directory rule, rise of Napoleon Bonaparte, abolition of slavery.', 'iess1', 1, 24, 30, 'completed', 100,
      ['Three Estates: Clergy (1st), Nobility (2nd), Commoners (3rd - bore all taxes)', 'Storming of Bastille on 14th July 1789 signalling fall of despotism', 'Reign of Terror (1793-1794) led by Maximilien Robespierre and use of guillotine'],
      [{t: 'Estates General', d: 'Political body where Three Estates sent representatives; Third Estate formed National Assembly on 20 June 1789'}],
      'Remember the Tennis Court Oath: 20 June 1789 promising not to disperse until a constitution was drafted.',
      {q: 'Explain the composition of the French society before the 1789 revolution.', a: 'Divided into Three Estates: 1st Estate (Clergy) and 2nd Estate (Nobility) owned 60% of land and paid no taxes; 3rd Estate (peasants, artisans, professionals) comprised 90% of population and paid all taxes.'},
      'Saying all three estates paid taxes; 1st and 2nd estates enjoyed exemption from all state taxes.'),
    createChapter('c9-soc-ch2', 2, 'Socialism in Europe and the Russian Revolution', 'Age of social change: Liberals, Radicals, Conservatives, Russian Empire in 1914 (Tsar Nicholas II), 1905 Revolution (Bloody Sunday), February Revolution 1917, October Revolution 1917 (Bolsheviks led by Vladimir Lenin), Civil War, Stalin’s collectivisation programme.', 'iess1', 2, 26, 32, 'completed', 100,
      ['Bloody Sunday 1905: peaceful workers fired upon, triggering 1905 revolution', 'Lenin’s April Theses: land to peasants, banks nationalised, war brought to close', 'October 1917 Bolshevik uprising seizing Petrograd', 'Stalin’s Collectivisation: elimination of Kulaks (rich peasants) and creation of Kolkhoz (collective farms)'],
      [{t: 'April Theses', d: 'Lenin\'s three demands: end World War I, transfer land to peasants, nationalise banks'}, {t: 'Kolkhoz', d: 'Collective farms in Soviet Union where peasants pooled land and implements'}],
      'Differentiate between February 1917 Revolution (abdication of Tsar) and October 1917 Revolution (Bolshevik takeover).',
      {q: 'What were the main demands of Vladimir Lenin\'s April Theses?', a: '1. War (World War I) be brought to a close. 2. Land be transferred to the peasants. 3. Banks be nationalised.'},
      'Confusing the Mensheviks (wanted open mass party) with Bolsheviks (disciplined cadre party led by Lenin).'),
    createChapter('c9-soc-ch3', 3, 'Nazism and the Rise of Hitler', 'Birth of Weimar Republic, Treaty of Versailles 1919 humiliation, Economic crisis and hyperinflation (1923), Rise of Adolf Hitler and Nazi Party, Destruction of democracy (Enabling Act 1933), Nazi worldview and racial hierarchy, Holocaust and concentration camps, Youth in Nazi Germany.', 'iess1', 3, 24, 30, 'not_started', 0,
      ['Treaty of Versailles forced Germany to accept war guilt, pay £6 billion reparations, lose 13% territory', 'Enabling Act (3 March 1933) established Hitler’s legal dictatorship', 'Nazi racial hierarchy: Nordic German Aryans at top, Jews viewed as racial antithesis', 'Propaganda machinery of Joseph Goebbels and extermination camps (Auschwitz)'],
      [{t: 'Enabling Act 1933', d: 'Gave Hitler all powers to sideline parliament and rule by decree'}, {t: 'Genocidal War', d: 'Systematic mass murder of selected innocent European civilians (6 million Jews)'}],
      'Understand the economic triggers that brought Hitler to power: hyperinflation (1923) and Great Depression (1929).',
      {q: 'What was the Enabling Act passed on 3 March 1933?', a: 'It established dictatorship in Germany, gave Hitler all powers to rule by decree without parliament, and banned all political parties and trade unions except Nazi party.'},
      'Attributing Hitler\'s rise solely to personal charisma; economic collapse and Treaty of Versailles were structural causes.'),
    createChapter('c9-soc-ch4', 4, 'Forest Society and Colonialism', 'Why deforestation? Commercial forestry under British rule, Dietrich Brandis (first Inspector General of Forests) and Indian Forest Act 1865/1878, Scientific forestry, impact on forest dwellers and shifting cultivation (swidden agriculture), Forest rebellions: Bastar rebellion 1910 (Gunda Dhur), Forest transformations in Java (Dutch colonial rule and Blandongdiensten system).', 'iess1', 4, 20, 25, 'not_started', 0,
      ['British exploited Indian forests for railway sleepers and Royal Navy timber', 'Dietrich Brandis set up Imperial Forest Research Institute at Dehradun (1906)', 'Bastar rebellion 1910 led by Gunda Dhur against reservation of two-thirds of forest', 'Surontiko Samin movement in Java resisting Dutch forest claims'],
      [{t: 'Scientific Forestry', d: 'System where natural diverse forests were cut down and replaced by one type of tree in straight rows'}, {t: 'Blandongdiensten', d: 'System of free labor imposed on Javanese villagers to cut and transport timber for Dutch'}],
      'Note how scientific forestry devastated biodiversity by planting monocultures like teak and pine.',
      {q: 'Why did the colonial government outlaw shifting cultivation (jhum)?', a: 'European foresters believed land used for shifting farming could not grow trees for railway timber, posed fire hazards, and made tax collection difficult.'},
      'Assuming "scientific forestry" was environmentally friendly; it was commercial monoculture.'),
    createChapter('c9-soc-ch5', 5, 'Pastoralists in the Modern World', 'Pastoral nomads and their movements: Mountains (Gaddis of Himachal, Gujjar Bakarwals of J&K, Gujjars of Garhwal), Plateaus, plains and deserts (Dhangars of Maharashtra, Raikas of Rajasthan, Banjaras), Colonial rule and pastoral life: Waste Land Rules, Forest Acts, Criminal Tribes Act 1871, Grazing Tax, Maasai pastoralists in colonial Africa (loss of grazing lands).', 'iess1', 5, 20, 25, 'not_started', 0,
      ['Nomadic pastoralists move seasonally between summer and winter pastures (transhumance)', 'Gujjar Bakarwals move to high meadows (Bugyals) in summer and low Shiwaliks in winter', 'Colonial grazing tax and Waste Land Rules converted grazing land to revenue-yielding agriculture', 'Maasai community lost over 60% of pre-colonial lands due to white settlement and game reserves (Serengeti)'],
      [{t: 'Transhumance', d: 'Seasonal movement of people with their livestock between fixed summer and winter pastures'}, {t: 'Criminal Tribes Act 1871', d: 'Colonial law classifying nomadic and pastoral communities as criminal by birth'}],
      'Understand how pastoral movements sustain ecology through cyclic manuring of harvested fields.',
      {q: 'How did the Criminal Tribes Act of 1871 affect pastoral communities in India?', a: 'They were forced to live in notified village settlements, were banned from moving without permits, and were closely monitored by colonial police.'},
      'Viewing pastoralism as an outdated primitive lifestyle; pastoralism is an ecologically adaptive strategy in arid/mountain zones.'),

    // Geography
    createChapter('c9-soc-ch6', 6, 'India - Size and Location', 'India\'s latitudinal (8°4\'N to 37°6\'N) and longitudinal (68°7\'E to 97°25\'E) extent, Tropic of Cancer (23°30\'N), Standard Meridian of India (82°30\'E passing through Mirzapur), Area (3.28 million sq km, 2.4% of world), India and the world, India\'s maritime neighbours (Sri Lanka and Maldives separated by Palk Strait).', 'iess2', 1, 14, 18, 'completed', 100,
      ['Total geographical area of India: 3.28 million sq. km (7th largest country)', 'Standard Meridian: 82°30\'E passing through Mirzapur (UP) avoiding 2-hour time lag between Gujarat and Arunachal', 'Palk Strait and Gulf of Mannar separate India from Sri Lanka'],
      [{t: 'Standard Meridian', d: '82°30\'E longitude chosen because it is central to India and multiple of 7°30\''}, {t: 'Tropic of Cancer (23°30\'N)', d: 'Divides India into almost two equal halves across 8 states'}],
      'List of 8 states through which Tropic of Cancer passes: Gujarat, Rajasthan, MP, Chhattisgarh, Jharkhand, WB, Tripura, Mizoram.',
      {q: 'Why is 82°30\'E chosen as the Standard Meridian of India?', a: 'There is a 2-hour time difference between Gujarat in west and Arunachal Pradesh in east. 82°30\'E passes centrally through Mirzapur, establishing uniform Indian Standard Time (IST).'},
      'Stating that India is 6th largest country; India is 7th largest (after Russia, Canada, USA, China, Brazil, Australia).'),
    createChapter('c9-soc-ch7', 7, 'Physical Features of India', 'Plate tectonics theory, Major physiographic divisions: The Himalayan Mountains (Himadri, Himachal, Shiwalik), Northern Plains (Bhabar, Terai, Bhangar, Khadar), Peninsular Plateau (Central Highlands & Deccan Plateau, Western & Eastern Ghats), Indian Desert (Thar), Coastal Plains (Western & Eastern coasts), Islands (Lakshadweep & Andaman and Nicobar).', 'iess2', 2, 22, 28, 'completed', 100,
      ['Three parallel Himalayan ranges: Greater Himalayas (Himadri), Lesser Himalayas (Himachal), Outer Himalayas (Shiwalik)', 'Northern plains: Bhabar (pebble belt where streams sink), Terai (marshy), Bhangar (old alluvium, kankar), Khadar (new fertile alluvium)', 'Western Ghats are continuous and higher (Anamudi 2695 m highest peak); Eastern Ghats are discontinuous'],
      [{t: 'Himadri', d: 'Northernmost Himalayan range, average elevation 6000 m, contains highest peaks (Everest, Kanchenjunga)'}, {t: 'Bhangar vs Khadar', d: 'Bhangar is old alluvium above flood plains; Khadar is young fertile alluvium renewed annually'}],
      'Map questions on Mountain peaks (K2, Kanchenjunga, Anamudi) and Mountain ranges (Aravalli, Vindhya, Satpura, Western/Eastern Ghats).',
      {q: 'Differentiate between Bhangar and Khadar soils.', a: 'Bhangar is older alluvium, found above flood levels, contains calcareous deposits (Kankar), and is less fertile. Khadar is newer, finer alluvium found in flood plains, renewed annually, and highly fertile.'},
      'Locating Western Ghats on east coast; Western Ghats parallel the Arabian Sea coast.'),
    createChapter('c9-soc-ch8', 8, 'Drainage', 'Drainage basin, water divide, Himalayan rivers (Indus, Ganga, Brahmaputra) vs Peninsular rivers (Narmada, Tapi, Godavari, Krishna, Cauvery, Mahanadi), Perennial vs Seasonal rivers, Lakes in India (Wular freshwater, Sambhar salt lake), Role of rivers in economy, River pollution and National River Conservation Plan (NRCP).', 'iess2', 3, 20, 26, 'not_started', 0,
      ['Himalayan rivers are perennial (fed by snow and rain) with dendritic drainage; Peninsular rivers are seasonal, rain-fed with trellis/rectangular patterns', 'Ganga river system: origin at Gangotri (Bhagirathi) joining Alaknanda at Devprayag; major tributaries Yamuna, Ghaghara, Gandak, Kosi', 'West-flowing Peninsular rivers forming estuaries: Narmada and Tapi; East-flowing rivers forming deltas: Godavari (Dakshin Ganga), Krishna, Cauvery'],
      [{t: 'Water Divide', d: 'Any elevated area such as a mountain or upland separating two drainage basins'}, {t: 'Dakshin Ganga', d: 'Godavari river, largest peninsular river basin (length ~1500 km)'}],
      'Map identification: Rivers (Indus, Satluj, Ganga, Yamuna, Brahmaputra, Narmada, Tapi, Godavari, Krishna, Cauvery) and Lakes (Wular, Sambhar, Chilika, Pulicat).',
      {q: 'Why are Himalayan rivers perennial while Peninsular rivers are seasonal?', a: 'Himalayan rivers originate in high glaciated mountains receiving water from melting snow throughout summer and monsoon rains. Peninsular rivers depend strictly on rainfall.'},
      'Listing Narmada as east-flowing; Narmada flows westward into the Arabian Sea through a rift valley.'),
    createChapter('c9-soc-ch9', 9, 'Climate', 'Weather vs Climate, Climatic controls (Latitude, Altitude, Pressure and Wind systems, Distance from the sea, Ocean currents, Relief features), Factors affecting India\'s climate, The Indian Monsoon (Mechanism: Inter Tropical Convergence Zone - ITCZ, El Nino, Southern Oscillation), The Seasons: Cold Weather (Winter), Hot Weather (Summer: Loo, Kalbaisakhi), Advancing Monsoon (Rainy), Retreating Monsoon (Transition: October heat), Monsoon as a unifying bond.', 'iess2', 4, 22, 28, 'not_started', 0,
      ['Six climatic controls of any place: Latitude, Altitude, Pressure/winds, Continentality, Ocean currents, Relief', 'Monsoon mechanism: Differential heating of land and water, shifting of ITCZ over Ganga plain, Tibetan plateau heating, Jet streams', 'El Nino: periodic warm ocean current along Peruvian coast disrupting Indian monsoon', 'October Heat: transition from rainy to dry winter characterized by high temperature and high humidity'],
      [{t: 'ITCZ', d: 'Inter Tropical Convergence Zone: broad trough of low pressure in equatorial latitudes where trade winds converge'}, {t: 'Kalbaisakhi', d: 'Calamity of month of Baisakh: localized thunderstorms with torrential rain and hail in West Bengal'}],
      'Mawsynram in Khasi Hills receives the highest average rainfall in the world.',
      {q: 'What is "October Heat" in India?', a: 'During retreat of monsoon in October-November, clear skies and moist soil cause daytime temperatures to rise high while nights are cool. The oppressively hot and humid day weather is called October heat.'},
      'Confusing Western Cyclonic Disturbances (winter rain in NW India) with Southwest Monsoon.'),
    createChapter('c9-soc-ch10', 10, 'Natural Vegetation and Wildlife', 'Factors affecting vegetation (Relief: land, soil; Climate: temperature, photoperiod, precipitation), Ecosystem and Biomes, Types of vegetation in India: Tropical Evergreen Forests, Tropical Deciduous Forests (Moist & Dry deciduous), Tropical Thorn Forests and Scrubs, Montane Forests, Mangrove Forests (Sundarbans, Sundari trees), Wildlife conservation (18 Biosphere Reserves in India, Project Tiger, Project Rhino).', 'iess2', 5, 20, 26, 'not_started', 0,
      ['Tropical Evergreen: rainfall >200 cm, no definite shedding season, ebony, mahogany, rosewood', 'Tropical Deciduous (Monsoon forests): most widespread in India (rainfall 70-200 cm), shed leaves for 6-8 weeks in dry summer; Sal, Teak, Peepal, Shisham', 'Mangrove forests in coastal deltas (Sundarbans), Sundari trees providing durable hard timber', '18 Biosphere reserves in India; 12 included in UNESCO World Network'],
      [{t: 'Tropical Deciduous', d: 'Most dominant forest type in India; divided into Moist (100-200 cm) and Dry (70-100 cm) deciduous'}, {t: 'Sundarbans', d: 'Tidal mangrove forest in Ganga-Brahmaputra delta, home of Royal Bengal Tiger'}],
      'Map work on vegetation types and Wildlife Sanctuaries / National Parks (Kaziranga, Jim Corbett, Ranthambore, Gir).',
      {q: 'Why are Tropical Evergreen forests also called Rainforests?', a: 'They grow in regions receiving over 200 cm annual rainfall, maintain high humidity, and remain green throughout the year as trees shed leaves at different times.'},
      'Marking Tropical Evergreen in Rajasthan; Rajasthan has Tropical Thorn and Scrub vegetation.'),
    createChapter('c9-soc-ch11', 11, 'Population', 'Population size and distribution (Census of India, UP most populous state, Sikkim least populous), Population growth and processes of change (Birth rate, Death rate, Migration: internal vs international), Age composition, Sex ratio, Literacy rates, Occupational structure, Adolescent population, National Population Policy (NPP 2000).', 'iess2', 6, 16, 22, 'not_started', 0,
      ['Census: official enumeration of population done every 10 years in India (first complete census 1881)', 'Three processes of population change: Births, Deaths, Migration (Natural increase = Birth rate - Death rate)', 'Sex ratio: number of females per 1000 males in the population', 'NPP 2000 focuses on free and compulsory school education up to age 14, reducing IMR, and addressing adolescent health'],
      [{t: 'Sex Ratio', d: 'Number of females per 1000 males in population (indicator of gender equality)'}, {t: 'NPP 2000', d: 'National Population Policy providing framework for reproductive health and family welfare'}],
      'Note that internal migration changes the distribution of population within the nation, but does not alter total population size.',
      {q: 'What are the three main components of population growth?', a: '1. Birth rate (number of live births per thousand persons). 2. Death rate (number of deaths per thousand persons). 3. Migration (movement of people across regions/territories).'},
      'Believing internal migration changes total national population size; only international migration changes national totals.'),

    // Civics
    createChapter('c9-soc-ch12', 12, 'What is Democracy? Why Democracy?', 'Simple definition of democracy, Key features of democracy: Rulers elected by people take major decisions (General Pervez Musharraf military coup in Pakistan), Free and fair electoral competition (China National People\'s Congress vs Mexico PRI six-year rule), One person, one vote, one value (Saudi Arabia, Estonia, Fiji violations), Rule of law and respect for rights (Robert Mugabe ZANU-PF in Zimbabwe), Arguments against democracy vs Arguments for democracy, Broader meanings of democracy.', 'iess3', 1, 18, 24, 'completed', 100,
      ['Democracy is a form of government in which rulers are elected by the people', 'Key features: final decision-making power with elected rulers, free & fair elections, universal adult franchise, rule of constitutional law', 'Democracy enhances dignity of citizens, allows correcting own mistakes, and improves quality of decision-making'],
      [{t: 'Democracy Core Definition', d: 'Form of government in which rulers are elected by the people on basis of equal political rights'}, {t: 'Rule of Law', d: 'Government rules within limits set by constitutional law and citizens\' rights'}],
      'Democracy does not guarantee economic prosperity, but provides the best mechanism for resolving social conflicts peacefully.',
      {q: 'State any three arguments against democracy.', a: '1. Leaders keep changing leading to political instability. 2. Democracy is all about political competition and power play with little morality. 3. Consultation leads to delays in decision-making.'},
      'Equating holding elections with true democracy; elections in China or Zimbabwe lacked genuine fairness.'),
    createChapter('c9-soc-ch13', 13, 'Constitutional Design', 'Democratic Constitution in South Africa (Apartheid struggle, Nelson Mandela 28 years imprisonment on Robben Island, 1994 new non-racial constitution), Why do we need a Constitution? Making of the Indian Constitution (Constituent Assembly, Dr. B.R. Ambedkar drafting chairman, adopted 26 Nov 1949, enacted 26 Jan 1950), Guiding values of Indian Constitution (The Preamble: Sovereign, Socialist, Secular, Democratic, Republic, Justice, Liberty, Equality, Fraternity).', 'iess3', 2, 20, 26, 'not_started', 0,
      ['Apartheid system ended on 26 April 1994 giving birth to multi-racial democratic South Africa', 'Functions of a constitution: generates trust, specifies government structure, limits power, expresses aspirations', 'Indian Constituent Assembly: 299 members, 3 years of rigorous debates, adopted on 26 Nov 1949 and in force on 26 Jan 1950', 'The Preamble is the soul/key to understanding the Indian Constitution'],
      [{t: 'Preamble', d: 'Introductory statement stating guiding philosophy, values, and core principles of the Constitution'}, {t: 'Sovereign', d: 'People have supreme right to make decisions on internal as well as external matters; no external power dictates to India'}],
      'Remember the two historic dates: Adoption (26 November 1949) vs Implementation/Republic Day (26 January 1950).',
      {q: 'Why should we accept the Constitution made by the Constituent Assembly more than 75 years ago?', a: '1. It represents consensus of the people of India, not just members. 2. Members came from diverse regions, religions, and linguistic groups. 3. The Constituent Assembly worked in an open, transparent, and consensus-driven manner.'},
      'Confusing the Chairman of Drafting Committee (Dr. B.R. Ambedkar) with President of Constituent Assembly (Dr. Rajendra Prasad).'),
    createChapter('c9-soc-ch14', 14, 'Electoral Politics', 'Why elections? What makes an election democratic? Is political competition good? System of elections in India: Electoral constituencies (Lok Sabha 543 constituencies), Reserved constituencies for SC/ST, Voters\' list (Universal Adult Franchise 18+), Nomination of candidates, Election campaign and Model Code of Conduct, Polling and counting of votes, What makes elections in India democratic? Independent Election Commission (ECI), Popular participation, Acceptance of election outcome.', 'iess3', 3, 20, 26, 'not_started', 0,
      ['Lok Sabha has 543 elected constituencies; 84 reserved for SC, 47 for ST', 'Model Code of Conduct: guidelines for political parties and candidates during election period', 'Election Commission of India (ECI) enjoys independence similar to the Judiciary', 'Use of Electronic Voting Machines (EVMs) and VVPAT ensuring transparency'],
      [{t: 'Universal Adult Franchise', d: 'Every citizen aged 18 and above has right to vote with each vote carrying equal value (one person, one vote)'}, {t: 'Model Code of Conduct', d: 'Set of norms agreed upon by all political parties regulating election campaigns and preventing misuse of state machinery'}],
      'Chief Election Commissioner (CEC) is appointed by President of India, but cannot be removed except by parliamentary impeachment.',
      {q: 'Explain any three powers of the Election Commission of India.', a: '1. Controls the conduct of elections from notification to declaration of results. 2. Implements Model Code of Conduct and punishes violators. 3. Orders repoll in polling booths if rigging occurs.'},
      'Believing government in power controls the Election Commission; ECI operates autonomously.'),
    createChapter('c9-soc-ch15', 15, 'Working of Institutions', 'How is a major policy decision taken? Office Memorandum (Mandal Commission 27% OBC reservation), Major decision makers: Prime Minister and Council of Ministers, Parliament (Lok Sabha vs Rajya Sabha: why Lok Sabha is more powerful in money matters), Political Executive vs Permanent Executive (Civil Servants), Prime Minister powers, Cabinet Secretariat, The President of India (nominal executive), The Judiciary (Supreme Court, Judicial Review, Public Interest Litigation - PIL).', 'iess3', 4, 22, 28, 'not_started', 0,
      ['Mandal Commission recommended 27% reservation for Socially and Educationally Backward Classes (SEBC)', 'Lok Sabha is more powerful than Rajya Sabha: money bills can originate only in Lok Sabha, Council of Ministers resigns if Lok Sabha passes no-confidence motion', 'Political Executive (ministers elected by people) vs Permanent Executive (bureaucrats/IAS)', 'Supreme Court is custodian of the Constitution; power of Judicial Review allows striking down unconstitutional laws'],
      [{t: 'Judicial Review', d: 'Power of Supreme Court and High Courts to determine constitutional validity of legislative acts and executive orders'}, {t: 'Public Interest Litigation (PIL)', d: 'Legal mechanism allowing any citizen to approach court for public cause without personal injury'}],
      'Money bills can ONLY be introduced in the Lok Sabha, and Rajya Sabha can delay them by at most 14 days.',
      {q: 'Why is the Lok Sabha more powerful than the Rajya Sabha in the Indian Parliament?', a: '1. In case of disagreement, joint session decision prevails due to larger Lok Sabha strength. 2. Lok Sabha exercises more powers in money bills (budget cannot be rejected by Rajya Sabha). 3. Lok Sabha controls Council of Ministers through no-confidence motion.'},
      'Thinking the President can run government independently; President acts strictly on aid and advice of Council of Ministers.'),
    createChapter('c9-soc-ch16', 16, 'Democratic Rights', 'Life without rights: Prison in Guantanamo Bay (US torture), Citizens\' rights in Saudi Arabia, Ethnic massacre in Kosovo (Slobodan Milosevic), Rights in a Democracy, Six Fundamental Rights in the Indian Constitution (Right to Equality, Right to Freedom, Right against Exploitation, Right to Freedom of Religion, Cultural and Educational Rights, Right to Constitutional Remedies - Article 32 "Heart and Soul of Constitution"), National Human Rights Commission (NHRC), Expanding scope of rights (RTI, Right to Education).', 'iess3', 5, 20, 26, 'not_started', 0,
      ['Guantanamo Bay and Kosovo illustrate consequences of state denial of basic human rights', 'Six Fundamental Rights enshrined in Part III of Indian Constitution (Articles 12-35)', 'Right to Constitutional Remedies (Article 32) called by Dr. B.R. Ambedkar the "Heart and Soul of Constitution"', 'Writs issued by Supreme Court / High Courts: Habeas Corpus, Mandamus, Prohibition, Quo Warranto, Certiorari'],
      [{t: 'Right to Equality', d: 'Abolition of untouchability (Art 17), equality before law (Art 14), non-discrimination (Art 15)'}, {t: 'Article 32 (Constitutional Remedies)', d: 'Enables citizens to directly approach Supreme Court if fundamental rights are violated'}],
      'Dr. B.R. Ambedkar called Article 32 (Right to Constitutional Remedies) the "Heart and Soul" of the Indian Constitution.',
      {q: 'Why is the Right to Constitutional Remedies considered the most important fundamental right?', a: 'Because it makes all other fundamental rights enforceable in a court of law; if any right is violated, a citizen can directly move the Supreme Court or High Court for enforcement through writs.'},
      'Omitting Article 32 when asked about the safeguard for fundamental rights.'),

    // Economics
    createChapter('c9-soc-ch17', 17, 'The Story of Village Palampur', 'Organisation of production: Four factors of production (Land, Labour, Physical Capital: Fixed vs Working Capital, Human Capital), Farming in Palampur: Land is fixed, Ways to increase production from same land (Multiple cropping, Green Revolution using HYV seeds, fertilizers, irrigation, modern machinery), Non-farm activities in Palampur (Dairy, Small scale manufacturing, Shopkeeping, Transport).', 'iess4', 1, 16, 22, 'completed', 100,
      ['Four requirements for production: Land, Labour, Capital (Fixed & Working), Human Capital', 'Fixed capital (tools, machines, buildings) vs Working capital (raw materials, cash in hand)', 'Green Revolution in late 1960s introduced HYV seeds, chemical fertilizers, tubewell irrigation in Punjab, Haryana, Western UP', 'Non-farm activities: 25% of Palampur working population engaged in dairy, transport, pottery, shopkeeping'],
      [{t: 'Four Factors of Production', d: 'Land, Labour, Physical Capital (Fixed & Working), Human Capital (Enterprise)'}, {t: 'Green Revolution', d: 'Introduction of High Yielding Varieties (HYV) seeds and modern inputs transforming grain production'}],
      'Green Revolution led to degradation of soil fertility and depletion of water table due to excessive chemical and tubewell usage.',
      {q: 'Differentiate between fixed capital and working capital with examples.', a: 'Fixed capital consists of tools, machines, and buildings that can be used in production over many years. Working capital consists of raw materials and money in hand that are consumed during production.'},
      'Confusing working capital (money, seeds) with fixed capital (tractors, tubewells).'),
    createChapter('c9-soc-ch18', 18, 'People as Resource', 'Overview of People as Resource, Economic activities by men and women (Market activities vs Non-market activities), Quality of Population: Education (Literacy rates, Sarva Shiksha Abhiyan, Mid-Day Meal scheme, Navodaya Vidyalayas) and Health (Life expectancy, infant mortality rate reduction), Unemployment: Seasonal unemployment, Disguised unemployment, Educated unemployment.', 'iess4', 2, 18, 25, 'not_started', 0,
      ['Human capital investment (education, training, medical care) yields high economic returns like physical capital', 'Sakal vs Vilas case study: education and health differentiate productive capabilities', 'Primary, Secondary, Tertiary sectors; Market activities (pay/profit) vs Non-market (self-consumption)', 'Unemployment types: Seasonal (farming off-season), Disguised (surplus family labor with zero marginal product), Educated (graduates without jobs)'],
      [{t: 'Human Capital', d: 'Stock of skill and productive knowledge embodied in a population through education and healthcare'}, {t: 'Sarva Shiksha Abhiyan', d: 'Flagship programme providing elementary education to all children aged 6 to 14 years'}],
      'Disguised unemployment is most prevalent in the rural agricultural sector of India.',
      {q: 'What is the difference between disguised unemployment and seasonal unemployment?', a: 'Seasonal unemployment happens when people cannot find jobs during certain off-season months of the year. Disguised unemployment occurs when more people are working on a task than required, and their removal does not reduce total output.'},
      'Classifying domestic household chores done by women as market activities (they are non-market unpaid work).'),
    createChapter('c9-soc-ch19', 19, 'Poverty as a Challenge', 'Two typical cases of poverty: Urban case (Ram Saran) and Rural case (Lakha Singh), Dimensions of poverty, Poverty as seen by social scientists: Social exclusion and Vulnerability, Poverty Line determination (Minimum calorie norm: 2400 kcal rural, 2100 kcal urban; income threshold), Poverty estimates in India, Vulnerable groups (SC, ST, rural agricultural labourers, urban casual labourers), Interstate disparities (Bihar and Odisha poorest), Global poverty trends (World Bank $2.15/day line), Causes of poverty (Colonial exploitation, population growth, unequal land distribution), Anti-poverty measures: Promotion of economic growth and Targeted programmes (MGNREGA 2005, PMRY, SGSY, AAY, PMGY).', 'iess4', 3, 20, 26, 'not_started', 0,
      ['Minimum nutritional calorie requirement: 2400 calories/person/day in rural areas, 2100 in urban areas', 'Social exclusion: living only in poor surroundings with poor people, excluded from social equality', 'Vulnerability: greater probability of specific communities (SC, ST, widows) remaining poor during crisis', 'Targeted anti-poverty programmes: MGNREGA (100 days wage employment), Antyodaya Anna Yojana (AAY subsidized food)'],
      [{t: 'Poverty Line Calorie Criteria', d: '2400 calories/day in rural areas (higher due to physical labor) vs 2100 calories/day in urban areas'}, {t: 'Social Exclusion', d: 'Process whereby individuals or groups are systematically blocked from facilities and benefits available to others'}],
      'Rural calorie requirement (2400 kcal) is HIGHER than urban (2100 kcal) because rural people do more heavy physical labor.',
      {q: 'Why is the calorie requirement higher in rural areas compared to urban areas?', a: 'Because rural people are engaged in more strenuous physical manual labor (farming, carrying loads) which burns more energy than urban sedentary occupations.'},
      'Writing that urban calorie requirement is higher; rural is higher (2400 vs 2100 kcal).'),
    createChapter('c9-soc-ch20', 20, 'Food Security in India', 'What is food security? (Availability, Accessibility, Affordability of food), Why food security? (Famine of Bengal 1943), Who are food-insecure? Food security in India: Green Revolution, Buffer Stock (FCI purchases wheat and paddy at Minimum Support Price - MSP), Public Distribution System (PDS / Ration shops: Fair Price Shops, BPL and APL ration cards, Antyodaya cards), Current status of PDS (revamped PDS, National Food Security Act 2013), Role of Cooperatives in food security (Amul in Gujarat, Mother Dairy in Delhi, Academy of Development Science grain banks in Maharashtra).', 'iess4', 4, 18, 24, 'not_started', 0,
      ['Three dimensions of food security: Availability (production + stock), Accessibility (within reach), Affordability (sufficient money)', 'Bengal Famine 1943: 30 lakh people died in Bengal due to starvation', 'Buffer Stock maintained by Food Corporation of India (FCI) through Minimum Support Price (MSP)', 'PDS provides food grains and sugar at subsidised issue price through Fair Price Shops', 'Cooperatives success stories: Amul (milk in Gujarat), Mother Dairy (Delhi), ADS grain banks (Maharashtra)'],
      [{t: 'Buffer Stock', d: 'Stock of food grains (wheat and rice) procured by government through FCI to distribute in deficit areas and during calamity'}, {t: 'Minimum Support Price (MSP)', d: 'Pre-announced price paid by government to farmers before sowing season to incentivize crop production'}],
      'Understand the role of National Food Security Act (NFSA 2013) covering 75% rural and 50% urban population.',
      {q: 'What is Buffer Stock and why is it created by the government?', a: 'Buffer Stock is the stock of food grains (wheat and rice) procured by FCI from surplus producing states at MSP. It is created to distribute grains in deficit areas and among poorer strata at prices lower than market rate, and to resolve food shortages during calamities.'},
      'Confusing Issue Price (price at which grains are sold in ration shops) with Minimum Support Price (price paid to farmers).')
  ];

  const englishChapters = [
    createChapter('c9-eng-ch1', 1, 'The Fun They Had', 'Isaac Asimov futuristic science fiction set in 2157: Margie and Tommy discovering an old printed book about mechanical teachers, telebooks, and old century human schools where children studied together happily.', 'iebe1', 1, 12, 18, 'completed', 100,
      ['Futuristic setting: year 2157 with mechanical teachers and telebooks', 'Margie\'s mechanical teacher inspects her failing geography tests', 'Nostalgia for old schools where human teachers taught children of same age together in a special building'],
      [{t: 'Theme', d: 'Human interaction and socialization in traditional schools cannot be replaced by isolated screen teaching'}, {t: 'Contrast', d: 'Solitary computer education vs joyful collective peer learning'}],
      'Focus on the contrast between Margie’s solitary computer screen room and the fun of traditional shared classrooms.',
      {q: 'What kind of school did Margie and Tommy have in 2157?', a: 'They had virtual classrooms in their own homes with individual mechanical teachers (computer screens), digital telebooks, and automated evaluation slots; they had no human teachers or classmates.'},
      'Thinking Margie hated learning; Margie hated the rigid mechanical teacher’s repetitive geography tests.'),
    createChapter('c9-eng-ch2', 2, 'The Sound of Music', 'Part I: Evelyn Glennie listens to sound without hearing it (profoundly deaf percussionist learning to feel music through body and vibrations). Part II: The Shehnai of Bismillah Khan (origin of Shehnai at royal court, Ustad Bismillah Khan elevating it to classical stage and Bharat Ratna award).', 'iebe1', 2, 18, 25, 'completed', 100,
      ['Evelyn Glennie becomes world-renowned solo percussionist despite losing hearing at age 11', 'Ron Forbes guides Evelyn to feel vibrations through barefoot contact with wooden stage', 'Bismillah Khan transforms pungi into melodic Shehnai at Red Fort on 15 August 1947'],
      [{t: 'Evelyn Glennie Inspiration', d: 'Disability is no obstacle if matched by unwavering determination and hard work'}, {t: 'Bismillah Khan Heritage', d: 'Rooted devotion to Ganga ghats, Banaras, and secular composite Indian music'}],
      'Evelyn’s quote: "Music pours in through every part of my body. It tingles in the skin, my cheekbones, and even in my hair."',
      {q: 'How did Evelyn Glennie learn to perceive musical notes after losing her hearing?', a: 'Percussionist Ron Forbes taught her not to listen through ears, but to sense vibrations through different parts of her body. Higher drums resonated in her upper waist and lower drums in her lower waist.'},
      'Confusing the Shehnai with the Pungi; the shehnai was invented by a barber (nai) in a Shah’s chamber to improve the shrill pungi.'),
    createChapter('c9-eng-ch3', 3, 'The Little Girl', 'Katherine Mansfield story of Kezia who fears her strict, authoritative father, accidentally tearing his important port speech papers to stuff a birthday pin-cushion gift, but discovering his deep hidden tenderness and protective love when nightmare strikes.', 'iebe1', 3, 14, 20, 'not_started', 0,
      ['Kezia stutters only in front of her imposing, giant-like father', 'Kezia compares her father with gentle neighbour Mr. Macdonald playing with his five children', 'Tearing father’s speech leads to punishment, but father comforts her tenderly during nightmare revealing his fatigue and genuine love'],
      [{t: 'Theme', d: 'Parental discipline often masks deep underlying affection and heavy work stress'}, {t: 'Climax', d: 'Father carries terrified Kezia to his bed, making her realise he has a "big heart"'}],
      'Understand Kezia’s transformation from terror of a harsh disciplinarian to empathy for an exhausted, hardworking father.',
      {q: 'Why was Kezia afraid of her father in the beginning?', a: 'Her father was strict, spoke in loud commanding tones, had large imposing hands, and never played with her, appearing like a harsh giant.'},
      'Judging the father as cruel; his severity was born of fatigue and concern for discipline.'),
    createChapter('c9-eng-ch4', 4, 'A Truly Beautiful Mind', 'Biographical sketch of Albert Einstein: late speaker considered abnormal, rebellious attitude toward rigid Munich schooling, revolutionary 1905 papers on Special Relativity (E = mc²), Brownian motion and Photoelectric Effect (Nobel Prize 1921), letter to President Roosevelt warning of Nazi atomic bomb, passionate crusade for world peace and nuclear disarmament.', 'iebe1', 4, 16, 22, 'not_started', 0,
      ['Einstein was slow to speak until age 2.5 and rejected rigid rote learning in Germany', 'Miracle year 1905: publications on Light quanta, Brownian motion, Special Relativity', 'Formula E = mc² linking energy and mass', 'Crusade against nuclear warfare: Einstein advocated for a World Government and democratic disarmament'],
      [{t: 'Truly Beautiful Mind', d: 'Einstein’s scientific genius was matched by his humanitarian concern for universal peace'}, {t: 'Mass-Energy Equivalence', d: 'E = mc² where c is speed of light'}],
      'Explain why the chapter is titled "A Truly Beautiful Mind": Einstein’s genius was dedicated to human welfare and peace, not destruction.',
      {q: 'Why did Einstein write a letter to American President Franklin D. Roosevelt in 1939?', a: 'To warn him that Nazi Germany had discovered nuclear fission and could build an atomic bomb capable of destroying an entire port and surrounding territory.'},
      'Assuming Einstein built the atomic bomb; he merely warned Roosevelt, and mourned deeply when it was used on Hiroshima and Nagasaki.'),
    createChapter('c9-eng-ch5', 5, 'The Snake and the Mirror', 'Vaikom Muhammad Basheer humorous narrative: homeopathic doctor in impoverished rented room contemplating vanity and handsome looks, suddenly wrapped by deadly cobra, only for snake to become captivated by its own reflection in the mirror, allowing doctor to escape.', 'iebe1', 5, 14, 20, 'not_started', 0,
      ['Homeopathic doctor admiring his mustache and smile in the mirror by kerosene lamp', 'A cold deadly cobra falls from roof and coils around doctor\'s left arm', 'The snake catches sight of its reflection in the mirror and slithers toward table to examine beauty at close range', 'Doctor runs for his life to friend’s house, returning next morning to find room looted by thief except dirty vest'],
      [{t: 'Irony & Humor', d: 'Both doctor and snake share identical human vanity admiring themselves in mirror'}, {t: 'Contrast', d: 'Grand vanity of poor doctor who owned only sixty rupees and one black coat'}],
      'Appreciate the subtle situational comedy when the thief leaves behind the doctor’s dirty vest out of insult.',
      {q: 'What made the snake uncoil itself from the doctor\'s arm?', a: 'The snake looked into the mirror on the table, seemed mesmerised by its own reflection, and slithered onto the table to admire itself, giving the doctor a chance to flee.'},
      'Thinking the doctor killed or fought the snake; the doctor sat motionless as a stone statue.'),
    createChapter('c9-eng-ch6', 6, 'My Childhood', 'Autobiographical extract from Wings of Fire by Dr. A.P.J. Abdul Kalam: upbringing in Rameswaram, parents Jainulabdeen and Ashiamma, childhood friends (Ramanadha Sastry, Aravindan, Sivaprakasan), breaking communal barriers, inspiring science teacher Sivasubramania Iyer and his orthodox wife.', 'iebe1', 6, 16, 22, 'not_started', 0,
      ['Kalam\'s early life in temple town of Rameswaram during Second World War', 'Secular harmony: Hindu and Muslim friends sitting together in classroom', 'New teacher attempts to separate Kalam from Ramanadha Sastry, reprimanded by head priest Lakshmana Sastry', 'Science teacher Sivasubramania Iyer breaks social taboos by inviting Kalam into kitchen'],
      [{t: 'Core Message', d: 'Inherent secular harmony and breaking prejudice through compassion and education'}, {t: 'Father\'s Wisdom', d: 'Jainulabdeen quoting Khalil Gibran: children are the sons and daughters of Life\'s longing for itself'}],
      'Focus on the character of Sivasubramania Iyer, who proved that one person can dismantle centuries of communal orthodoxy.',
      {q: 'What happened when a new teacher came to Kalam\'s class in fifth standard?', a: 'He could not tolerate a Muslim boy wearing a cap sitting next to a Hindu priest\'s son wearing sacred thread, and ordered Kalam to go and sit on the back bench.'},
      'Saying Kalam’s family was wealthy; they lived a simple, austere life with strict discipline.'),
    createChapter('c9-eng-ch7', 7, 'Reach for the Top', 'Part I: Santosh Yadav (only woman in world to scale Mount Everest twice, defying orthodox conservative Haryana village norms). Part II: Maria Sharapova (Russian tennis sensation winning Wimbledon at 17, sacrifices, relentless training and mental toughness in Florida).', 'iebe1', 7, 16, 22, 'not_started', 0,
      ['Santosh Yadav insists on studying in Delhi, scales Everest twice, saves fellow climber Mohan Singh by sharing oxygen', 'Maria Sharapova moved to USA at age 9 without mother, enduring loneliness and bullying to reach World No. 1', 'Common traits: extraordinary grit, physical endurance, unwavering focus, patriotism'],
      [{t: 'Santosh Yadav Feat', d: 'First woman to scale Mount Everest twice; brought down 500 kg garbage from Himalayas'}, {t: 'Maria Sharapova Mantram', d: '"I am very, very competitive. I work hard at what I do. It\'s my job."'}],
      'Compare the obstacles faced by Santosh (conservative patriarchal society) and Maria (isolation, language barrier, bullying).',
      {q: 'How did Santosh Yadav save the life of a fellow climber on Mount Everest?', a: 'She shared her own oxygen cylinder with fellow mountaineer Mohan Singh, who would have died without her timely assistance.'},
      'Thinking Santosh gave in to traditional marriage demands at age 16; she threatened never to marry unless properly educated.'),
    createChapter('c9-eng-ch8', 8, 'Kathmandu', 'Vikram Seth travelogue excerpt from From Heaven Lake: vivid sights, sounds, and religious atmosphere of Kathmandu, holy Pashupatinath temple (febrile confusion, priests, monkeys) vs peaceful serene Baudhnath stupa (Buddhist haven of quiet), flute seller playing haunting melodies.', 'iebe1', 8, 14, 20, 'not_started', 0,
      ['Pashupatinath temple: atmosphere of "febrile confusion", saffron-clad priests, monkeys, holy Bagmati cremation', 'Baudhnath Stupa: profound stillness, silence, immense white dome, Tibetan immigrant shops', 'The flute seller: plays effortlessly with universal breath uniting all humanity through music'],
      [{t: 'Pashupatinath vs Baudhnath', d: 'Chaotic Hindu devotional fervor vs quiet contemplative Buddhist sanctuary'}, {t: 'Flute Symbolism', d: 'Universal musical instrument common to every culture, living in the human breath'}],
      'Contrast the two religious shrines: Pashupatinath (chaotic Hindu temple) vs Baudhnath (serene Buddhist stupa).',
      {q: 'How does Vikram Seth describe the flute seller at Kathmandu?', a: 'He holds a pole with fifty protruding flutes resembling a porcupine, plays selected tunes slowly without aggressive selling, and pours the universal music of human breath into the market.'},
      'Assuming Baudhnath stupa is noisy; Baudhnath is remarkably tranquil with a sense of stillness.'),
    createChapter('c9-eng-ch9', 9, 'If I Were You', 'Douglas James witty play: cultured playwright Gerrard confronting an armed intruder who intends to murder him and steal his identity, Gerrard keeping his wits, convincing intruder that he is a criminal himself on the run, and locking him inside a cupboard.', 'iebe1', 9, 14, 20, 'not_started', 0,
      ['Intruder breaks into Gerrard\'s lonely cottage planning identity theft to escape police', 'Gerrard uses presence of mind, theatrical wit, and calm psychological manipulation', 'Fabricates a false persona as an elusive criminal on the run with disguise props', 'Tricks intruder into looking into garage exit, which is actually a dark cupboard, locking him in'],
      [{t: 'Theme', d: 'Intellectual composure and quick wit triumph over brute force and panic'}, {t: 'Gerrard\'s Wit', d: 'Playwright profession allows him to construct a spontaneous credible drama'}],
      'Note how Gerrard’s cool banter unsettles the intruder’s violent plan.',
      {q: 'How did Gerrard outwit the intruder who had come to kill him?', a: 'Gerrard convinced him that he himself was a dangerous criminal facing police arrest, led him to inspect an escape door which was actually a cupboard, pushed him inside, and locked him.'},
      'Thinking Gerrard engaged in a violent physical fight; he defeated the intruder entirely by psychological wit.'),
    createChapter('c9-eng-ch10', 10, 'The Lost Child', 'Mulk Raj Anand touching story from Moments: young boy visiting spring fair with parents, enchanted by toys, dragonflies, sweets, flowers, and roundabout swing, but getting separated and losing all desire for earthly pleasures, crying only for his mother and father.', 'iemo1', 1, 14, 20, 'not_started', 0,
      ['Child’s innocent fascination with mustard fields, gulab jamun, garland of gulmohar, balloons, flute music', 'Roundabout attraction causes separation from parents', 'Kind stranger offers all fair treats (sweets, balloons, swing), but the child rejects everything crying: "I want my mother, I want my father!"'],
      [{t: 'Theme', d: 'Parents are a child\'s ultimate world; material attractions become meaningless without family security'}, {t: 'Symbolism of Fair', d: 'The alluring sensory world and the sudden vulnerability of solitude'}],
      'The open ending: the child’s intense sobs for his parents highlight the primacy of parental love.',
      {q: 'What was the child\'s reaction when the kind stranger offered him sweets, balloons, and a ride on the roundabout?', a: 'He turned his eyes away from every offer, wept inconsolably, and repeatedly cried: "I want my mother, I want my father!"'},
      'Believing the child accepted the stranger’s gifts; he refused all luxuries wanting only his parents.')
  ];

  const hindiChapters = [
    createChapter('c9-hin-ch1', 1, 'दो बैलों की कथा (प्रेमचंद)', 'हीरा और मोती दो स्वाभिमानी बैलों की कथा, झूरी का स्नेह, गया का क्रूर व्यवहार, छोटी बच्ची का आत्मीय प्रेम, कांजीहौस की दीवार तोड़ना, कसाई से बचकर घर वापसी, पशुओं में मानवीय संवेदना और आजादी का मूल्य।', 'ihks1', 1, 16, 22, 'completed', 100,
      ['गधे और बैल को सीधा और सहनशील मानना लेकिन स्वाभिमान पर आंच आने पर विद्रोह करना', 'हीरा और मोती का मूक भाषा में विचार-विनिमय और गहरी मित्रता', 'कांजीहौस की कच्ची दीवार सींगों से तोड़कर कमजोर पशुओं को मुक्त कराना', 'प्रेमचंद का संदेश: आजादी बिना संघर्ष के नहीं मिलती'],
      [{t: 'स्वाभिमान और स्वतंत्रता', d: 'पशु भी स्वतंत्रता और स्नेह के आकांक्षी होते हैं; आजादी के लिए बार-बार लड़ना पड़ता है'}, {t: 'मित्रता की मिसाल', d: 'हीरा-मोती एक-दूसरे के लिए जान की बाजी लगा देते हैं'}],
      'प्रेमचंद जी की यथार्थवादी शैली और मुहावरेदार भाषा पर विशेष ध्यान दें।',
      {q: 'कांजीहौस में हीरा और मोती ने अपनी वीरता और परोपकार का परिचय किस प्रकार दिया?', a: 'मोती ने सींग मार-मारकर कांजीहौस की कच्ची दीवार गिरा दी जिससे वहां बंद गधे, बकरियां, घोड़े भागकर आजाद हो गए, यद्यपि हीरा के बंधे होने के कारण मोती स्वयं नहीं भागा।'},
      'गधे को मूर्ख समझना; पाठ में गधे के सीधेपन को संतों के सद्गुणों से जोड़ा गया है।'),
    createChapter('c9-hin-ch2', 2, 'ल्हासा की ओर (राहुल सांकृत्यायन)', 'तिब्बत की यात्रा का सजीव वृत्तांत, 1929-30 में भिक्षु के छद्म वेश में यात्रा (डांडे की विकट घाटियां, डाकुओं का भय), सुमति का परिचय, तिब्बती समाज (जाति-पांति और पर्दा प्रथा रहित), शेखर विहार में पोथियों का अध्ययन।', 'ihks1', 2, 16, 22, 'not_started', 0,
      ['लेखक की तिब्बत यात्रा डाकुओं से बचने के लिए भीखमंगे के वेश में', 'तिब्बती समाज की विशेषताएं: जाति-पांति, छुआछूत और पर्दा प्रथा का न होना; खुले विचार', 'डांडे थोंगला के 17-18 हजार फीट ऊंचे खतरनाक रास्ते और डाकुओं का आतंक', 'मठों में रखी हस्तलिखित पोथियों (कंजुर) का अध्ययन'],
      [{t: 'तिब्बती समाज', d: 'अतिथि सत्कार, महिलाओं की स्वतंत्रता, छुआछूत का अभाव, लेकिन कानून व्यवस्था की कमजोरी'}, {t: 'यात्रा साहित्य', d: 'भौगोलिक, सांस्कृतिक और सामाजिक यथार्थ का प्रामाणिक दस्तावेज'}],
      'डाकुओं के आतंक और बंदूक कानून न होने के कारण तिब्बत में लाठी की तरह पिस्तौल लेकर घूमने का प्रसंग महत्वपूर्ण है।',
      {q: 'उस समय के तिब्बत में हथियार का कानून न रहने के कारण यात्रियों को किस प्रकार का भय बना रहता था?', a: 'हथियार कानून न होने के कारण लोग लाठी की तरह पिस्तौल और बंदूक लेकर घूमते थे, और डाकू पहले आदमी को मार देते थे फिर तलाशी लेते थे कि पैसा है या नहीं।'},
      'तिब्बत को रूढ़िवादी समाज समझना; तिब्बती समाज उस समय भी पर्दा प्रथा और छुआछूत से मुक्त था।'),
    createChapter('c9-hin-ch3', 3, 'उपभोक्तावाद की संस्कृति (श्यामाचरण दुबे)', 'बाजारवाद और दिखावे की संस्कृति पर गंभीर सामाजिक विमर्श, विज्ञापनों की सम्मोहन शक्ति, उत्पाद की गुणवत्ता के स्थान पर प्रतिष्ठा का दिखावा, सामाजिक ताने-बाने और मानवीय मूल्यों का क्षरण, गांधीजी की चेतावनी।', 'ihks1', 3, 14, 20, 'not_started', 0,
      ['बदलती जीवनशैली: उपभोग भोग ही सुख बन गया है', 'विज्ञापनों की लुभावनी दुनिया द्वारा कृत्रिम आवश्यकताओं का निर्माण', 'साबुन, टूथपेस्ट से लेकर घड़ियों और अंतिम संस्कार तक प्रतिष्ठा का अंधानुकरण', 'गांधीजी का विचार: हम खिड़कियां खुली रखें लेकिन अपनी बुनियाद पर कायम रहें'],
      [{t: 'उपभोक्तावाद', d: 'आवश्यकता के स्थान पर दिखावे और विज्ञापनों के दबाव में वस्तुएं खरीदने की अंधी होड़'}, {t: 'सामाजिक प्रभाव', d: 'अमीर-गरीब के बीच बढ़ती खाई, अशांति और सांस्कृतिक अस्मिता का क्षरण'}],
      'उपभोक्तावाद कैसे हमारी सांस्कृतिक अस्मिता को नष्ट कर रहा है, इस दीर्घ उत्तरीय प्रश्न का अभ्यास करें।',
      {q: 'लेखक के अनुसार उपभोक्तावादी संस्कृति हमारे दैनिक जीवन को किस प्रकार प्रभावित कर रही है?', a: 'यह हमें उत्पादों का दास बना रही है, हमारी वास्तविक आवश्यकताओं के बजाय कृत्रिम इच्छाएं पैदा कर रही है और समाज में दिखावे तथा मानसिक अशांति को बढ़ावा दे रही है।'},
      'उपभोक्तावाद को केवल आर्थिक समृद्धि मानना; यह सामाजिक असमानता और मूल्यों का क्षरण है।'),
    createChapter('c9-hin-ch4', 4, 'सांवले सपनों की याद (जाबिर हुसैन)', 'प्रसिद्ध पक्षी विज्ञानी सालिम अली का व्यक्ति-चित्र, डायरी शैली में संस्मरण, पक्षियों के प्रति उनकी अगाध निष्ठा, साइलेंट वैली को बचाने के लिए चौधरी चरण सिंह से मुलाकात, प्रकृति को सालिम अली की आंखों से देखना।', 'ihks1', 4, 14, 20, 'not_started', 0,
      ['सालिम अली की 'फॉल ऑफ ए स्पैरो' (गोरैया की मौत जिसने उनका जीवन पक्षी प्रेम की ओर मोड़ा)', 'केरल की 'साइलेंट वैली' को रेगिस्तानी हवाओं से बचाने के लिए प्रधानमंत्री चौधरी चरण सिंह से मिलना', 'प्रकृति के प्रति गहरी संवेदनशीलता: वे प्रकृति को अपनी दुनिया बना चुके थे', 'जाबिर हुसैन की काव्यात्मक भाषा और संस्मरण शैली'],
      [{t: 'सालिम अली का व्यक्तित्व', d: 'अनथक पक्षी खोजी (बर्डवॉचर), दूरबीन गले में लटकाए प्रकृति के रहस्यों की खोज में समर्पित'}, {t: 'सांवले सपने', d: 'अधूरी आकांक्षाएं और सालिम अली के चले जाने से उत्पन्न शून्यता'}],
      'बचपन में एयरगन से घायल हुई नीलकंठ गोरैया ने कैसे सालिम अली का जीवन बदल दिया, इसे याद रखें।',
      {q: 'सालिम अली ने पूर्व प्रधानमंत्री चौधरी चरण सिंह के सामने पर्यावरण से संबंधित किन खतरों का चित्र खींचा था?', a: 'उन्होंने केरल की 'साइलेंट वैली' को रेगिस्तानी गर्म हवा के झोंकों से होने वाले विनाश और पारिस्थितिक संकट से बचाने की गुहार लगाई थी।'},
      'सालिम अली को केवल शिकारी समझना; वे भारत के सबसे महान पक्षी संरक्षक और ऑर्निथोलॉजिस्ट थे।'),
    createChapter('c9-hin-ch5', 5, 'प्रेमचंद के फटे जूते (हरिशंकर परसाई)', 'प्रेमचंद के फटे जूते के माध्यम से सामाजिक कुरीतियों और दिखावे की प्रवृत्ति पर तीखा व्यंग्य, परसाई जी का हास्य-व्यंग्य शिल्प, साहित्य के पुरखे की सादगी बनाम समाज का दोहरा आचरण, अंगुली का इशारा।', 'ihks1', 5, 14, 20, 'not_started', 0,
      ['प्रेमचंद का पत्नी के साथ फोटो: कैनवस का जूता फटा हुआ जिसमें से पैर की अंगुली बाहर झांक रही है', 'लेखक का व्यंग्य: लोग फोटो खिंचाने के लिए जूते, कपड़े यहां तक कि बीवी तक मांग लेते हैं पर प्रेमचंद सादगी में जीते हैं', 'जूता हमेशा टोपी से कीमती रहा है (शक्ति और धन के आगे प्रतिभा का झुकना)', 'प्रेमचंद ने ठोकर मारकर जूते फाड़े: रूढ़ियों और भ्रष्ट व्यवस्था पर प्रहार का प्रतीक'],
      [{t: 'व्यंग्य का मर्म', d: 'दिखावे की झूठी संस्कृति पर चोट और प्रेमचंद के स्वाभिमानी, समझौताहीन व्यक्तित्व की प्रशंसा'}, {t: 'फटे जूते का प्रतीक', d: 'सामाजिक बुराइयों पर ठोकर मारने का संघर्ष'}],
      'जूते और टोपी के आनुपातिक महत्व वाले अंश से अक्सर व्याख्यात्मक प्रश्न पूछे जाते हैं।',
      {q: 'लेखक ने प्रेमचंद को "साहित्यिक पुरखा" क्यों कहा है और उनके जूते फटने का क्या कारण बताया है?', a: 'क्योंकि वे हिंदी गद्य के सिरमौर और कालजयी कथाकार हैं। उनके जूते घिसने से नहीं, बल्कि समाज के टीलों (रूढ़ियों और आडंबरों) पर लगातार ठोकर मारने से फटे हैं।'},
      'प्रेमचंद को दरिद्र या असहाय समझना; वे स्वाभिमानी और समझौता न करने वाले महान लेखक थे।'),
    createChapter('c9-hin-ch6', 6, 'मेरे बचपन के दिन (महादेवी वर्मा)', 'महादेवी वर्मा का आत्मकथात्मक संस्मरण, कन्या जन्म पर परिवार का उल्लास (बाबा का देवी रूप में स्वागत), क्रास्थवेट गर्ल्स कॉलेज का माहौल, सुभद्रा कुमारी चौहान से मित्रता, कविता लेखन की शुरुआत, गांधीजी को चांदी का कटोरा भेंट करना।', 'ihks1', 6, 14, 20, 'not_started', 0,
      ['उस युग में लड़कियों के प्रति उपेक्षा के विपरीत महादेवी के परिवार में उनका आदर और शिक्षा का प्रबंध', 'क्रास्थवेट गर्ल्स कॉलेज में सुभद्रा कुमारी चौहान के साथ छात्रावास में कवित्व का प्रस्फुटन', 'कवि सम्मेलनों में प्रथम पुरस्कार में मिला चांदी का कटोरा गांधीजी को देश सेवा के लिए दान देना', 'सांप्रदायिक सद्भाव का वातावरण: बेगम साहिबा का परिवार और महादेवी का घर'],
      [{t: 'स्त्री शिक्षा व सम्मान', d: 'रूढ़िवादिता के विरुद्ध कन्या जन्म का उत्सव और उच्च शिक्षा का अवसर'}, {t: 'सांप्रदायिक सौहार्द', d: 'हिंदू और मुस्लिम परिवारों के बीच पारिवारिक अपनत्व और साझा त्योहार'}],
      'महादेवी वर्मा और सुभद्रा कुमारी चौहान की छात्रावास की बाल सखित्व की स्मृतियों को समझें।',
      {q: 'महादेवी वर्मा ने अपने बचपन में मिली चांदी के कटोरे का क्या किया?', a: 'कवि सम्मेलन में प्रथम पुरस्कार में मिले नक्काशीदार चांदी के कटोरे को उन्होंने आनंद भवन में गांधीजी को देश के स्वतंत्रता आंदोलन कोष के लिए समर्पित कर दिया।'},
      'महादेवी वर्मा के परिवार को दकियानूसी समझना; उनके परिवार में स्त्री शिक्षा को विशेष प्रोत्साहन मिला था।'),
    createChapter('c9-hin-ch7', 7, 'साखियाँ एवं सबद (कबीर)', 'कबीर की साखियों में ज्ञान, प्रेम और सदाचार का उपदेश, जाति-पांति और बाह्य आडंबरों का खंडन, मानसरोवर का प्रतीक, ईश्वर की सर्वव्यापकता (मोको कहाँ ढूँढे रे बन्दे), सहज समाधि।', 'ihks1', 7, 12, 18, 'not_started', 0,
      ['साखी: मानसरोवर सुभर जल, हंसा केलि कराहिं (मुक्त आत्मा प्रभु भक्ति में लीन)', 'जाति-पांति, हिंदू-मुस्लिम के भेदभाव से ऊपर उठकर निष्पक्ष भक्ति का उपदेश', 'सबद: ईश्वर मंदिर, मस्जिद या काबा-कैलाश में नहीं, बल्कि हर प्राणी के अंतरतम में विद्यमान है'],
      [{t: 'कबीर की सधुक्कड़ी भाषा', d: 'अवधी, ब्रज, पंजाबी, राजस्थानी शब्दों का सहज लोक मिश्रण'}, {t: 'निर्गुण भक्ति', d: 'कर्मकांडों, तिलक, छापा, तीर्थ, नमाज के बाह्य प्रदर्शन का प्रखर विरोध'}],
      'कबीर के रहस्यवाद और दोहों के नीतिपरक अर्थ को आत्मसात करें।',
      {q: 'कबीर के अनुसार ईश्वर को मनुष्य कहाँ-कहाँ ढूँढता फिरता है और वह वास्तव में कहाँ मिलता है?', a: 'मनुष्य ईश्वर को मंदिर, मस्जिद, काबा, कैलाश और योग-वैराग्य में खोजता है, जबकि ईश्वर प्रत्येक प्राणी के भीतर श्वासों की श्वास में उपस्थित है।'},
      'कबीर को केवल धर्म-विरोधी समझना; वे बाह्य आडंबरों के विरोधी और सच्ची आत्मानुभूति के पक्षधर थे।'),
    createChapter('c9-hin-ch8', 8, 'वाख (ललद्यद)', 'कश्मीरी कवयित्री ललद्यद के चार वाख, जीवन रूपी नाव को कच्चे धागे से खींचना, हठयोग की व्यर्थता (सुषुम सेतु पर बीत गया दिन), समभावी बनने का उपदेश (सांकल खुलेगी बंद द्वार की), ज्ञानी वही है जो आत्मज्ञान प्राप्त करे।', 'ihks1', 8, 10, 16, 'not_started', 0,
      ['कच्चे धागे की रस्सी से जीवन नौका खींचने का भावपूर्ण रूपक', 'माध्यम मार्ग का संदेश: न खाकर कुछ पाएगा नहीं, न खाकर बनेगा अहंकारी; सम खा तभी खुलेगी सांकल', 'सुषुम सेतु (हठयोग की नाड़ी साधना) के अंत में जेब टटोलने पर 'कौड़ी न पाई' (सत्कर्मों का अभाव)', 'शिव (ईश्वर) सर्वत्र विद्यमान है, हिंदू-मुसलमान में भेद न करना ही सच्चा आत्मज्ञान है'],
      [{t: 'वाख काव्य विधा', d: 'कश्मीरी भाषा की चार पंक्तियों वाली गेय एवं अर्थपूर्ण छंद रचना'}, {t: 'मुख्य संदेश', d: 'हठयोग और आडंबरों से मुक्ति, सहज प्रेम और सद्कर्मों द्वारा प्रभु मिलन'}],
      '"जेब टटोली कौड़ी न पाई" का लाक्षणिक अर्थ (सत्कर्म रूपी पूंजी का न होना) बार-बार पूछा जाता है।',
      {q: 'कवयित्री ललद्यद ने बंद द्वार की सांकल खोलने के लिए क्या उपाय सुझाया है?', a: 'कवयित्री ने अंतःकरण और बाह्य इंद्रियों का निग्रह कर समभावी (मध्यम मार्ग अपनाने) की सलाह दी है, जिससे अहंकार मिटेगा और चेतना व्यापक होगी।'},
      'वाख को केवल हठयोग साधना मानना; यह हठयोग की विफलता और सहज प्रेम का संदेश है।'),
    createChapter('c9-hin-ch9', 9, 'सवैये (रसखान)', 'रसखान के सवैयों में कृष्ण और ब्रजभूमि के प्रति अनन्य समर्पण, अगले जन्म में मनुष्य, पशु, पत्थर या पक्षी बनकर गोकुल और कालिंदी तीर पर बसने की कामना, कृष्ण की लाठी और कंबल पर तीनों लोकों का राज्य न्यौछावर करना, गोपियों का कृष्ण रूप धारण करना।', 'ihks1', 9, 12, 18, 'not_started', 0,
      ['मानुष हौं तो वही रसखानि बसौं ब्रज गोकुल गाँव के ग्वारन (पुनर्जन्म में ब्रज वास की इच्छा)', 'लकुटी अरु कामरिया पर राज तिहूँ पुर को तजि डारौं (कृष्ण के सान्निध्य पर सर्वस्व न्योछावर)', 'गोपियों का कृष्ण के मुकुट, पीतांबर धारण करना पर अधरों पर मुरली न रखना (मुरली से सौतिया डाह)'],
      [{t: 'सवैय्या छंद', d: 'ब्रजभाषा का अत्यंत मधुर, संगीतमय और वर्णिक छंद'}, {t: 'अनन्य कृष्ण भक्ति', d: 'मुस्लिम कवि रसखान का ब्रज और कृष्ण के प्रति अगाध प्रेम'}],
      'रसखान की ब्रजभाषा की माधुर्यता और सवैयों के आंतरिक संगीत पर ध्यान दें।',
      {q: 'रसखान अगले जन्म में किन-किन रूपों में ब्रज में ही क्यों जन्म लेना चाहते हैं?', a: 'रसखान कृष्ण की लीलाभूमि से इतना प्रेम करते हैं कि वे ग्वाला, नंद की गाय, गोवर्धन पर्वत का पत्थर या यमुना तट के कदंब पर पक्षी बनकर सदा कृष्ण का सामीप्य पाना चाहते हैं।'},
      'गोपियों को मुरली से प्रेम समझना; गोपियां मुरली को अपनी सौत मानकर उससे ईर्ष्या करती हैं।'),
    createChapter('c9-hin-ch10', 10, 'कैदी और कोकिला (माखनलाल चतुर्वेदी)', 'भारतीय स्वतंत्रता संग्राम के दौरान अंग्रेजी जेल में बंद स्वतंत्रता सेनानी की व्यथा, अर्धरात्रि में कूकी कोयल से संवाद, जेल की काली दीवारों, बेड़ियों और कोल्हू के बैल का वर्णन, ब्रिटिश हुकूमत का काला शासन, आजादी के लिए आत्मोत्सर्ग का संकल्प।', 'ihks1', 10, 14, 20, 'not_started', 0,
      ['ब्रिटिश जेल में कैदियों पर होने वाले अमानवीय अत्याचारों का मार्मिक चित्रण', 'आधी रात में कोयल की कूक को दावानल की ज्वालाएं और क्रांति का संदेश मानना', 'हथकड़ियों को ब्रिटिश राज का गहना मानकर गर्व करना', 'माखनलाल चतुर्वेदी की ओजस्वी राष्ट्रीय चेतना और एक भारतीय आत्मा का स्वर'],
      [{t: 'राष्ट्रीय चेतना', d: 'स्वाधीनता सेनानियों के आत्मबल, कष्ट-सहन और देशप्रेम का जीवंत दस्तावेज'}, {t: 'हथकड़ी = गहना', d: 'देश के लिए पहनी गई बेड़ियों को स्वाभिमान का आभूषण मानना'}],
      'कवि ने हथकड़ियों को ब्रिटिश राज का गहना क्यों कहा है, यह प्रश्न बोर्ड और गृह परीक्षाओं का मुख्य केंद्र है।',
      {q: 'कवि माखनलाल चतुर्वेदी ने कोयल के कूकने के किन-किन कारणों की संभावना व्यक्त की है?', a: 'कवि अनुमान लगाते हैं कि कोयल या तो कैदियों के लिए कोई गुप्त संदेश लाई है, या उसने देश में लगी क्रांति की दावानल देख ली है, अथवा वह जेल के अत्याचारों पर रुदन कर रही है।'},
      'कोयल के कूकने को सामान्य मधुर गान समझना; कवि ने उसे वेदना और विद्रोह का स्वर माना है।')
  ];

  return [
    {
      id: 'c9-math',
      name: 'Mathematics',
      code: 'MATH-09',
      color: '#2B6DEF',
      bgLight: '#EBF2FE',
      icon: 'fa-solid fa-calculator',
      gradient: 'linear-gradient(135deg, #2B6DEF 0%, #174BB8 100%)',
      chaptersCount: mathChapters.length,
      completedCount: mathChapters.filter(c => c.status === 'completed').length,
      chapters: mathChapters
    },
    {
      id: 'c9-science',
      name: 'Science',
      code: 'SCI-09',
      color: '#059669',
      bgLight: '#E6F4EA',
      icon: 'fa-solid fa-flask-vial',
      gradient: 'linear-gradient(135deg, #059669 0%, #047857 100%)',
      chaptersCount: scienceChapters.length,
      completedCount: scienceChapters.filter(c => c.status === 'completed').length,
      chapters: scienceChapters
    },
    {
      id: 'c9-social',
      name: 'Social Science',
      code: 'SST-09',
      color: '#D97706',
      bgLight: '#FEF3C7',
      icon: 'fa-solid fa-earth-americas',
      gradient: 'linear-gradient(135deg, #D97706 0%, #B45309 100%)',
      chaptersCount: socialChapters.length,
      completedCount: socialChapters.filter(c => c.status === 'completed').length,
      chapters: socialChapters
    },
    {
      id: 'c9-english',
      name: 'English',
      code: 'ENG-09',
      color: '#7C3AED',
      bgLight: '#EDE9FE',
      icon: 'fa-solid fa-book-open-reader',
      gradient: 'linear-gradient(135deg, #7C3AED 0%, #6D28D9 100%)',
      chaptersCount: englishChapters.length,
      completedCount: englishChapters.filter(c => c.status === 'completed').length,
      chapters: englishChapters
    },
    {
      id: 'c9-hindi',
      name: 'Hindi',
      code: 'HIN-09',
      color: '#DC2626',
      bgLight: '#FEE2E2',
      icon: 'fa-solid fa-pen-nib',
      gradient: 'linear-gradient(135deg, #DC2626 0%, #B91C1C 100%)',
      chaptersCount: hindiChapters.length,
      completedCount: hindiChapters.filter(c => c.status === 'completed').length,
      chapters: hindiChapters
    }
  ];
}

module.exports = { getClass9Subjects };
