const { createChapter } = require('./helper');

function getClass10Subjects() {
  const mathChapters = [
    createChapter('math-ch1', 1, 'Real Numbers', 'Fundamental Theorem of Arithmetic, irrational proofs for √2, √3, √5, prime factorisation HCF/LCM.', 'jemh1', 1, 18, 25, 'completed', 100,
      ['Fundamental Theorem of Arithmetic statement & applications', 'Proof of irrationality of √2, √3, √5 using contradiction', 'Prime factorisation method for HCF and LCM'],
      [{t: 'HCF × LCM', d: 'HCF(a, b) × LCM(a, b) = a × b (for 2 numbers)'}, {t: 'Prime Factorisation', d: 'Every composite = unique product of primes'}],
      'Remember that HCF × LCM = a × b only works for 2 numbers, never for 3 numbers.',
      {q: 'Given HCF(306, 657) = 9, find LCM(306, 657).', a: 'LCM = (306 × 657) / 9 = 22,338.'},
      'Do not apply HCF × LCM rule for 3 numbers.'),
    createChapter('math-ch2', 2, 'Polynomials', 'Geometrical meaning of zeroes, relationship between zeroes and coefficients of quadratic polynomials.', 'jemh1', 2, 22, 30, 'completed', 100,
      ['Zeroes of a polynomial from graph (x-intercepts)', 'Sum of zeroes: α + β = -b/a', 'Product of zeroes: αβ = c/a'],
      [{t: 'Sum of zeroes', d: 'α + β = -b/a'}, {t: 'Product of zeroes', d: 'αβ = c/a'}, {t: 'Quadratic Polynomial', d: 'k[x² - (α + β)x + αβ]'}],
      'The number of zeroes is the exact number of times the curve intersects the x-axis, not y-axis.',
      {q: 'Find a quadratic polynomial whose zeroes are 2 and -3.', a: 'Sum = -1, Product = -6. Polynomial: x² - (-1)x + (-6) = x² + x - 6.'},
      'Confusing the negative sign in sum of zeroes: it is -b/a, not b/a.'),
    createChapter('math-ch3', 3, 'Pair of Linear Equations in Two Variables', 'Graphical method, Substitution method, and Elimination method for solving linear pairs.', 'jemh1', 3, 26, 35, 'completed', 100,
      ['Consistency conditions: a1/a2 ≠ b1/b2 (Unique solution)', 'a1/a2 = b1/b2 = c1/c2 (Infinitely many solutions)', 'a1/a2 = b1/b2 ≠ c1/c2 (No solution / Inconsistent)'],
      [{t: 'Unique Solution', d: 'a1/a2 ≠ b1/b2 (Intersecting lines)'}, {t: 'No Solution', d: 'a1/a2 = b1/b2 ≠ c1/c2 (Parallel lines)'}, {t: 'Coincident Lines', d: 'a1/a2 = b1/b2 = c1/c2 (Dependent consistent)'}],
      'Cross-multiplication has been removed from the 2026 rationalised syllabus; master Elimination and Substitution.',
      {q: 'For what value of k will equations x + 2y = 3 and 5x + ky = 7 have no solution?', a: 'Condition: 1/5 = 2/k ≠ 3/7 ⇒ k = 10.'},
      'Forgetting to align equations in standard form ax + by + c = 0 before comparing ratios.'),
    createChapter('math-ch4', 4, 'Quadratic Equations', 'Standard form ax² + bx + c = 0, factorisation method, and nature of roots via discriminant D = b² - 4ac.', 'jemh1', 4, 20, 30, 'completed', 100,
      ['Quadratic formula: x = (-b ± √D) / 2a', 'Discriminant D = b² - 4ac', 'D > 0: two distinct real roots; D = 0: two equal real roots; D < 0: no real roots'],
      [{t: 'Quadratic Formula', d: 'x = [-b ± √(b² - 4ac)] / (2a)'}, {t: 'Discriminant', d: 'D = b² - 4ac'}],
      'If roots are real and equal, always set D = 0 to solve for unknown parameter k.',
      {q: 'Find the values of k for which 2x² + kx + 3 = 0 has two equal roots.', a: 'D = k² - 4(2)(3) = 0 ⇒ k² = 24 ⇒ k = ±2√6.'},
      'Omitting the ± sign when taking square roots.'),
    createChapter('math-ch5', 5, 'Arithmetic Progressions', 'nth term of an AP: an = a + (n-1)d and sum of first n terms: Sn = n/2[2a + (n-1)d].', 'jemh1', 5, 24, 30, 'completed', 100,
      ['nth term: an = a + (n - 1)d', 'Common difference: d = ak+1 - ak', 'Sum of n terms: Sn = n/2 (a + l) where l is last term'],
      [{t: 'General Term', d: 'an = a + (n - 1)d'}, {t: 'Sum of n terms', d: 'Sn = (n/2)[2a + (n - 1)d] = (n/2)(a + l)'}],
      'n must always be a positive integer! If you get a fraction or negative value for n, check your algebra.',
      {q: 'Find the 20th term of the AP: 2, 7, 12, ...', a: 'a = 2, d = 5. a20 = 2 + (19)(5) = 2 + 95 = 97.'},
      'Taking d as second term minus first term when it is decreasing (d can be negative).'),
    createChapter('math-ch6', 6, 'Triangles', 'Similarity of triangles, Basic Proportionality Theorem (Thales Theorem) and its converse, AAA, SSS, SAS criteria.', 'jemh1', 6, 28, 40, 'in_progress', 60,
      ['Basic Proportionality Theorem (BPT) proof & converse', 'Criteria for similarity: AAA, SSS, SAS', 'Ratio of corresponding sides in similar triangles'],
      [{t: 'Thales Theorem (BPT)', d: 'If DE || BC, then AD/DB = AE/EC'}, {t: 'Similarity Criteria', d: 'AAA, SSS, SAS ratios must be in corresponding order'}],
      'BPT proof is one of the most frequently asked 5-mark theorem proofs in CBSE Board exams.',
      {q: 'In △ABC, DE || BC such that AD = 1.5 cm, DB = 3 cm, AE = 1 cm. Find EC.', a: 'By BPT, AD/DB = AE/EC ⇒ 1.5/3 = 1/EC ⇒ EC = 2 cm.'},
      'Writing triangle similarity without matching vertex correspondence (e.g. △ABC ~ △EDF vs △DEF).'),
    createChapter('math-ch7', 7, 'Coordinate Geometry', 'Distance formula, Section formula (internal division), and coordinates of midpoint.', 'jemh1', 7, 20, 25, 'in_progress', 45,
      ['Distance formula: d = √[(x2 - x1)² + (y2 - y1)²]', 'Section formula: P(x, y) = [(m1x2 + m2x1)/(m1+m2), (m1y2 + m2y1)/(m1+m2)]', 'Midpoint formula: ((x1 + x2)/2, (y1 + y2)/2)'],
      [{t: 'Distance Formula', d: 'd = √[(x2 - x1)² + (y2 - y1)²]'}, {t: 'Section Formula', d: 'x = (m1x2 + m2x1)/(m1 + m2), y = (m1y2 + m2y1)/(m1 + m2)'}, {t: 'Midpoint Formula', d: '((x1+x2)/2, (y1+y2)/2)'}],
      'When finding ratio k:1, let ratio be k:1 instead of m:n to reduce equations to one variable.',
      {q: 'Find the midpoint of segment joining (2, -5) and (-4, 7).', a: 'Midpoint = ((2 + -4)/2, (-5 + 7)/2) = (-2/2, 2/2) = (-1, 1).'},
      'Mixing up x-coordinates and y-coordinates inside the distance formula square.'),
    createChapter('math-ch8', 8, 'Introduction to Trigonometry', 'Trigonometric ratios of acute angles, values at 0°, 30°, 45°, 60°, 90°, and identity sin²θ + cos²θ = 1.', 'jemh1', 8, 22, 30, 'in_progress', 30,
      ['Ratios: sin, cos, tan, cot, sec, cosec in right triangle', 'Specific angle values table (0° to 90°)', 'Fundamental identity: sin²θ + cos²θ = 1, 1 + tan²θ = sec²θ, 1 + cot²θ = cosec²θ'],
      [{t: 'Fundamental Identity', d: 'sin²θ + cos²θ = 1'}, {t: 'Tangent Ratio', d: 'tan θ = sin θ / cos θ = Opp / Adj'}, {t: 'Values at 45°', d: 'sin 45° = 1/√2, cos 45° = 1/√2, tan 45° = 1'}],
      'Memorise the table using the finger rule (0/4, 1/4, 2/4, 3/4, 4/4 under square root).',
      {q: 'If sin θ = 3/5, find cos θ and tan θ.', a: 'cos θ = √(1 - (3/5)²) = 4/5. tan θ = (3/5)/(4/5) = 3/4.'},
      'Confusing sec θ (1/cos θ) with cosec θ (1/sin θ).'),
    createChapter('math-ch9', 9, 'Some Applications of Trigonometry', 'Heights and distances, line of sight, angle of elevation, angle of depression.', 'jemh1', 9, 16, 25, 'not_started', 0,
      ['Angle of elevation vs Angle of depression (alternate interior angles are equal)', 'One right triangle vs Two right triangle situations', 'Using tan θ = Perpendicular / Base for height and distance problems'],
      [{t: 'Angle of Elevation', d: 'Angle formed by line of sight with horizontal when object is above'}, {t: 'Angle of Depression', d: 'Angle formed with horizontal when object is below'}],
      'Draw the diagram first with proper labels! In board marking schemes, correct diagram carries 1 mark.',
      {q: 'A tower stands vertically on ground. From a point 15 m away from base, angle of elevation is 60°. Find tower height.', a: 'tan 60° = h / 15 ⇒ √3 = h / 15 ⇒ h = 15√3 m.'},
      'Taking angle of depression with the vertical instead of horizontal line.'),
    createChapter('math-ch10', 10, 'Circles', 'Tangent to a circle, radius-tangent perpendicularity theorem, tangents from an external point are equal in length.', 'jemh1', 10, 18, 25, 'not_started', 0,
      ['Theorem 10.1: Tangent is perpendicular to radius at point of contact', 'Theorem 10.2: Tangents drawn from external point to circle are equal', 'Properties of cyclic quadrilaterals and circumscribed polygons'],
      [{t: 'Radius-Tangent Theorem', d: 'OP ⊥ AB at point of contact P'}, {t: 'Equal Tangents Theorem', d: 'PA = PB from external point P to circle'}],
      'Use the fact that △OPA ≅ △OPB by RHS congruence for Theorem 10.2 proofs.',
      {q: 'If tangents PA and PB from a point P to a circle with centre O are inclined to each other at an angle of 80°, find ∠POA.', a: '∠AOB = 180° - 80° = 100°. ∠POA = 100° / 2 = 50°.'},
      'Forgetting that opposite angles in a quadrilateral circumscribing a circle subtend supplementary angles at centre.'),
    createChapter('math-ch11', 11, 'Areas Related to Circles', 'Perimeter and area of circle, area of sector of circle, area of segment of circle.', 'jemh1', 11, 18, 25, 'not_started', 0,
      ['Area of sector: (θ/360°) × πr²', 'Length of arc: (θ/360°) × 2πr', 'Area of segment = Area of sector - Area of corresponding triangle'],
      [{t: 'Sector Area', d: '(θ/360°) × πr²'}, {t: 'Arc Length', d: '(θ/360°) × 2πr'}, {t: 'Minor Segment Area', d: '(θ/360°)πr² - (1/2)r² sin θ'}],
      'For triangle area with angle θ = 60° use (√3/4)r²; for θ = 90° use (1/2)r²; for general use (1/2)r² sin θ.',
      {q: 'Find area of a sector of circle with radius 6 cm if angle of sector is 60° (use π = 22/7).', a: 'Area = (60/360) × (22/7) × 36 = (1/6) × (22/7) × 36 = 132/7 = 18.86 cm².'},
      'Confusing sector (pie slice) with segment (region between chord and arc).'),
    createChapter('math-ch12', 12, 'Surface Areas and Volumes', 'Surface areas and volumes of combinations of solids (cubes, cuboids, spheres, hemispheres, right circular cylinders, cones).', 'jemh1', 12, 22, 30, 'not_started', 0,
      ['Total surface area of combination = visible surfaces added together', 'Volume of combination = sum of individual volumes', 'Cone slant height: l = √(r² + h²)'],
      [{t: 'Cylinder Volume', d: 'πr²h'}, {t: 'Cone Volume', d: '(1/3)πr²h'}, {t: 'Sphere Volume', d: '(4/3)πr³'}, {t: 'Hemisphere Volume', d: '(2/3)πr³'}, {t: 'Cone CSA', d: 'πrl where l = √(r²+h²)'}],
      'When two solids are joined (e.g. cone on cylinder), do NOT add their TSAs! Add their CSAs plus visible bases.',
      {q: 'A solid is in shape of a cone standing on a hemisphere with both their radii being 1 cm and height of cone is equal to its radius. Find volume in terms of π.', a: 'V = (1/3)πr²h + (2/3)πr³ = (1/3)π(1)³ + (2/3)π(1)³ = π cm³.'},
      'Adding overlapping contact surfaces when calculating total surface area of combined solid.'),
    createChapter('math-ch13', 13, 'Statistics', 'Mean, median and mode of grouped data, empirical relationship: Mode = 3 Median - 2 Mean.', 'jemh1', 13, 24, 35, 'not_started', 0,
      ['Mean of grouped data: Direct, Assumed Mean (a + Σfidi/Σfi), and Step Deviation methods', 'Mode = l + [(f1 - f0)/(2f1 - f0 - f2)] × h', 'Median = l + [(n/2 - cf)/f] × h'],
      [{t: 'Empirical Relationship', d: 'Mode = 3 Median - 2 Mean'}, {t: 'Mean Formula', d: 'x̄ = Σfixi / Σfi'}, {t: 'Median Class', d: 'Class whose cumulative frequency is just greater than n/2'}],
      'Remember the empirical formula as "3 Medians minus 2 Means equals Mode" (3 - 2 = 1).',
      {q: 'If the mean of a frequency distribution is 25 and median is 26, calculate mode.', a: 'Mode = 3(Median) - 2(Mean) = 3(26) - 2(25) = 78 - 50 = 28.'},
      'Taking cf from the median class instead of the preceding class in median formula.'),
    createChapter('math-ch14', 14, 'Probability', 'Classical definition of probability, elementary events, complementary events P(E) + P(not E) = 1.', 'jemh1', 14, 18, 25, 'not_started', 0,
      ['P(E) = (Number of favourable outcomes) / (Total number of possible outcomes)', '0 ≤ P(E) ≤ 1 for any event E', 'P(Sure Event) = 1, P(Impossible Event) = 0'],
      [{t: 'Probability Rule', d: 'P(E) = Favourable / Total'}, {t: 'Complement Rule', d: 'P(E) + P(E̅) = 1'}, {t: 'Deck of Cards', d: '52 cards: 4 suits of 13 cards each, 12 face cards (K, Q, J)'}],
      'In playing cards: total cards = 52. Red cards = 26 (Hearts & Diamonds), Black cards = 26 (Spades & Clubs). Face cards = 12.',
      {q: 'A card is drawn from a well-shuffled pack of 52 cards. Find probability of getting a king of red colour.', a: 'Total = 52. Red kings = 2 (Heart & Diamond). P = 2/52 = 1/26.'},
      'Writing probability values greater than 1 or negative numbers.')
  ];

  const scienceChapters = [
    createChapter('sci-ch1', 1, 'Chemical Reactions and Equations', 'Balanced chemical equations, types of reactions: combination, decomposition, displacement, double displacement, oxidation and reduction.', 'jesc1', 1, 16, 25, 'completed', 100,
      ['Law of conservation of mass in balanced equations', 'Types: Combination, Decomposition, Displacement, Double Displacement', 'Oxidation (loss of e⁻ / gain of O), Reduction (gain of e⁻ / loss of O)'],
      [{t: 'Combination', d: 'A + B → AB'}, {t: 'Decomposition', d: 'AB → A + B (Thermal, Electrolytic, Photolytic)'}, {t: 'Displacement', d: 'More reactive metal displaces less reactive metal'}],
      'Always specify physical states (s, l, g, aq) in reactions for full marks in CBSE.',
      {q: 'Why should a magnesium ribbon be cleaned before burning in air?', a: 'To remove the protective layer of basic magnesium carbonate/oxide formed by reaction with moist air.'},
      'Confusing oxidising agent with substance oxidised (the substance that gets reduced is the oxidising agent).'),
    createChapter('sci-ch2', 2, 'Acids, Bases and Salts', 'Properties of acids and bases, pH scale and its daily life importance, preparation and uses of Bleaching Powder, Baking Soda, Washing Soda, Plaster of Paris.', 'jesc1', 2, 20, 30, 'completed', 100,
      ['Acid + Metal → Salt + H2↑ (Pop sound test)', 'pH scale: 0 (strongly acidic) to 14 (strongly basic)', 'Chemical formulas: CaOCl2, NaHCO3, Na2CO3·10H2O, CaSO4·1/2H2O'],
      [{t: 'Plaster of Paris', d: 'CaSO4·1/2H2O + 1.5 H2O → CaSO4·2H2O (Gypsum)'}, {t: 'Bleaching Powder', d: 'Ca(OH)2 + Cl2 → CaOCl2 + H2O'}, {t: 'Baking Soda', d: 'NaHCO3 (Sodium hydrogen carbonate)'}],
      'POP must be stored in moisture-proof containers because it absorbs water to set into hard gypsum.',
      {q: 'Why does dry HCl gas not change the colour of dry litmus paper?', a: 'Dry HCl does not form H+ (aq) / hydronium ions in absence of water, so it does not exhibit acidic properties.'},
      'Adding water to acid instead of adding acid slowly to water with constant stirring (highly exothermic).'),
    createChapter('sci-ch3', 3, 'Metals and Non-metals', 'Physical and chemical properties of metals and non-metals, Reactivity series, Ionic compounds properties, Metallurgy: Roasting, Calcination, Refining.', 'jesc1', 3, 24, 30, 'completed', 100,
      ['Reactivity series: K > Na > Ca > Mg > Al > Zn > Fe > Pb > [H] > Cu > Hg > Ag > Au', 'Ionic bonds: transfer of electrons, high MP/BP, conduct electricity in molten/aqueous state', 'Roasting (excess air, sulphide ores) vs Calcination (limited air, carbonate ores)'],
      [{t: 'Roasting', d: '2ZnS + 3O2 → 2ZnO + 2SO2 (Sulphide ore heated in excess air)'}, {t: 'Calcination', d: 'ZnCO3 → ZnO + CO2 (Carbonate ore heated in limited air)'}, {t: 'Thermite Reaction', d: 'Fe2O3 + 2Al → 2Fe(l) + Al2O3 + Heat (Joining railway tracks)'}],
      'Mnemonic for reactivity series: "Please Stop Calling Me A Careless Zebra, Instead Try Learning How Copper Saves Gold".',
      {q: 'Why are ionic compounds solid and hard with high melting points?', a: 'Due to strong electrostatic forces of attraction between oppositely charged ions.'},
      'Confusing roasting (sulphide) with calcination (carbonate). Remember C for Calcination = Carbonate.'),
    createChapter('sci-ch4', 4, 'Carbon and its Compounds', 'Covalent bonding, Versatile nature of carbon (catenation and tetravalency), Homologous series, IUPAC nomenclature, Functional groups, Soaps and detergents.', 'jesc1', 4, 26, 35, 'completed', 100,
      ['Tetravalency and catenation properties of carbon', 'Homologous series: differ by -CH2- unit and 14 u molecular mass', 'Saponification: Ester + NaOH → Soap + Alcohol', 'Micelle formation and cleansing action of soap'],
      [{t: 'Alkane', d: 'CnH2n+2'}, {t: 'Alkene', d: 'CnH2n'}, {t: 'Alkyne', d: 'CnH2n-2'}, {t: 'Esterification', d: 'CH3COOH + C2H5OH (conc. H2SO4) → CH3COOC2H5 + H2O'}],
      'Soaps do not work in hard water because they form insoluble precipitates (scum) with Ca²⁺ and Mg²⁺ ions; detergents do work in hard water.',
      {q: 'What is a homologous series? State any two characteristics.', a: 'A family of organic compounds having the same functional group. Characteristics: successive members differ by -CH2-, and have similar chemical properties.'},
      'Drawing carbon with 3 or 5 bonds; carbon is strictly tetravalent (4 covalent bonds).'),
    createChapter('sci-ch5', 5, 'Life Processes', 'Nutrition (autotrophic & heterotrophic, photosynthesis, human digestive system), Respiration (aerobic vs anaerobic), Transportation (human circulatory system & double circulation), Excretion (nephron structure & urine formation).', 'jesc1', 5, 28, 40, 'completed', 100,
      ['Photosynthesis equation and site (chloroplast)', 'Aerobic vs Anaerobic respiration (ATP yield and products)', 'Human heart: Double circulation and separation of oxygenated/deoxygenated blood', 'Nephron: ultrafiltration, selective reabsorption, and tubular secretion'],
      [{t: 'Photosynthesis', d: '6CO2 + 12H2O (light, chlorophyll) → C6H12O6 + 6O2 + 6H2O'}, {t: 'Double Circulation', d: 'Pulmonary circulation (heart-lungs) + Systemic circulation (heart-body)'}, {t: 'Functional unit of kidney', d: 'Nephron'}],
      'Practice drawing diagrams of the Human Heart and the Structure of Nephron; they carry 3-5 marks.',
      {q: 'Why is double circulation necessary in human beings?', a: 'To keep oxygenated and deoxygenated blood separate, fulfilling the high energy requirements of warm-blooded humans.'},
      'Confusing pulmonary artery (carries deoxygenated blood) with pulmonary vein (carries oxygenated blood).'),
    createChapter('sci-ch6', 6, 'Control and Coordination', 'Nervous system in animals: Neuron structure, Reflex arc, Human brain (Forebrain, Midbrain, Hindbrain), Plant hormones (Auxin, Gibberellin, Cytokinin, Abscisic acid), Tropic movements.', 'jesc1', 6, 22, 30, 'in_progress', 60,
      ['Neuron structure: Dendrite → Cyton → Axon → Nerve Ending (Synapse chemical transmission)', 'Reflex arc pathway: Receptor → Sensory neuron → Relay neuron (Spinal cord) → Motor neuron → Effector', 'Plant hormones: Auxin (cell elongation), Cytokinin (cell division), ABA (growth inhibitor)'],
      [{t: 'Synapse', d: 'Gap between two neurons where electrical impulse converts to chemical neurotransmitter'}, {t: 'Phototropism', d: 'Auxin diffuses to shaded side, causing cells on that side to grow longer'}],
      'Reflex actions are coordinated by the spinal cord to allow rapid protective responses without waiting for conscious thought.',
      {q: 'What is the function of receptors in our body? State what happens when receptors do not work properly.', a: 'Receptors detect environmental stimuli. If impaired, external signals are not received, compromising protective reflexes.'},
      'Labeling the sensory and motor neurons in reverse order in the reflex arc diagram.'),
    createChapter('sci-ch7', 7, 'How do Organisms Reproduce?', 'Asexual reproduction (Fission, Fragmentation, Regeneration, Budding, Vegetative propagation, Spore formation), Sexual reproduction in flowering plants, Human reproductive system, Menstrual cycle, Contraceptive methods.', 'jesc1', 7, 24, 30, 'in_progress', 40,
      ['Asexual vs Sexual reproduction advantages', 'Flower reproduction: Pollination, Double fertilisation (syngamy + triple fusion)', 'Male (Testes, Vas deferens) & Female (Ovary, Fallopian tube, Uterus) systems', 'Barrier, chemical, and surgical contraceptive methods'],
      [{t: 'Double Fertilisation', d: 'Syngamy (zygote 2n) + Triple Fusion (endosperm 3n)'}, {t: 'Site of Fertilisation', d: 'Fallopian tube (Oviduct)'}, {t: 'Placenta', d: 'Disc-shaped vascular tissue providing glucose & O2 to fetus and removing wastes'}],
      'Fertilisation occurs specifically in the Fallopian tube (oviduct), while implantation occurs in the uterine lining.',
      {q: 'What is the role of the seminal vesicles and the prostate gland?', a: 'They secrete fluid that provides nutrition to the sperms and makes their transport easier.'},
      'Confusing pollination (transfer of pollen) with fertilisation (fusion of gametes).'),
    createChapter('sci-ch8', 8, 'Heredity', 'Heredity and inherited traits, Mendel’s laws of inheritance (Monohybrid cross 3:1, Dihybrid cross 9:3:3:1), Sex determination in human beings (XX and XY chromosomes).', 'jesc1', 8, 18, 25, 'in_progress', 30,
      ['Mendel’s monohybrid cross phenotypic ratio 3:1, genotypic ratio 1:2:1', 'Dihybrid cross phenotypic ratio 9:3:3:1', 'Sex determination: Father determines child gender (50% X sperm, 50% Y sperm)'],
      [{t: 'Monohybrid Phenotypic Ratio', d: '3 : 1 (Tall : Dwarf)'}, {t: 'Monohybrid Genotypic Ratio', d: '1 : 2 : 1 (TT : Tt : tt)'}, {t: 'Sex Chromosomes', d: 'Female = 44 + XX, Male = 44 + XY'}],
      'Evolution has been removed from the rationalised 2026 NCERT Class 10 syllabus; focus purely on Heredity and Mendel.',
      {q: 'Why are women not responsible for the sex of the child?', a: 'Women produce only one type of ovum (22 + X). The father produces two types of sperms (22 + X or 22 + Y); the father determines sex.'},
      'Writing phenotypic ratio when genotypic ratio is asked in Mendel’s crosses.'),
    createChapter('sci-ch9', 9, 'Light – Reflection and Refraction', 'Spherical mirrors, mirror formula, magnification, refraction of light, Snell’s law, refractive index, lenses, lens formula, power of a lens.', 'jesc1', 9, 26, 35, 'not_started', 0,
      ['Mirror formula: 1/f = 1/v + 1/u, Magnification: m = -v/u = h\'/h', 'Snell\'s Law: sin i / sin r = constant = n21', 'Lens formula: 1/f = 1/v - 1/u, Magnification: m = +v/u = h\'/h', 'Power of lens: P = 1 / f (in metres), unit: Dioptre (D)'],
      [{t: 'Mirror Formula', d: '1/f = 1/v + 1/u'}, {t: 'Lens Formula', d: '1/f = 1/v - 1/u'}, {t: 'Power of Lens', d: 'P = 1/f(m) Dioptres (Convex = +D, Concave = -D)'}],
      'Always follow the Cartesian Sign Convention: object distance u is ALWAYS negative.',
      {q: 'A convex lens of focal length 20 cm produces a real image at 40 cm. Find object distance.', a: '1/v - 1/u = 1/f ⇒ 1/40 - 1/u = 1/20 ⇒ 1/u = 1/40 - 1/20 = -1/40 ⇒ u = -40 cm.'},
      'Confusing the sign in mirror formula (+1/u) with lens formula (-1/u).'),
    createChapter('sci-ch10', 10, 'The Human Eye and the Colourful World', 'Structure of human eye, power of accommodation, defects of vision (Myopia, Hypermetropia, Presbyopia) and corrections, refraction through prism, dispersion, atmospheric refraction, scattering of light (Tyndall effect, blue sky, reddish sun).', 'jesc1', 10, 20, 25, 'not_started', 0,
      ['Myopia (near-sightedness, elongated eyeball): corrected by Concave lens', 'Hypermetropia (far-sightedness, shortened eyeball): corrected by Convex lens', 'Dispersion of white light by prism into VIBGYOR', 'Atmospheric refraction: twinkling of stars, advanced sunrise and delayed sunset', 'Rayleigh scattering: Intensity ∝ 1/λ⁴ (Blue light scattered most)'],
      [{t: 'Myopia Correction', d: 'Concave lens of appropriate power'}, {t: 'Hypermetropia Correction', d: 'Convex lens of appropriate power'}, {t: 'Atmospheric Refraction', d: 'Causes advance sunrise by 2 mins and delayed sunset by 2 mins'}],
      'Draw the ray diagrams showing defective eye and corrected eye for Myopia/Hypermetropia clearly.',
      {q: 'Why do stars twinkle but planets do not?', a: 'Stars are point sources far away, subject to atmospheric turbulence. Planets are extended sources, so variations average out.'},
      'Prescribing convex lens for myopia (myopia requires diverging concave lens).'),
    createChapter('sci-ch11', 11, 'Electricity', 'Electric current and circuit, electric potential and potential difference, Ohm’s law, factors on which resistance depends (resistivity), resistors in series and parallel, heating effect of electric current (Joule’s law), electric power.', 'jesc1', 11, 24, 30, 'not_started', 0,
      ['Ohm\'s Law: V = IR (at constant temperature)', 'Resistance: R = ρ (l / A)', 'Series: Rs = R1 + R2 + R3, Parallel: 1/Rp = 1/R1 + 1/R2 + 1/R3', 'Joule\'s Heating: H = I²Rt', 'Power: P = VI = I²R = V²/R, Commercial unit 1 kWh = 3.6 × 10⁶ J'],
      [{t: 'Ohm\'s Law', d: 'V = IR'}, {t: 'Resistivity Formula', d: 'R = ρ(l / A)'}, {t: '1 kWh in Joules', d: '3.6 × 10⁶ Joules'}],
      'In parallel circuits, voltage is identical across all branches; in series circuits, current is identical.',
      {q: 'A wire of resistance 20 Ω is cut into 4 equal parts and joined in parallel. Find equivalent resistance.', a: 'Each part = 5 Ω. 1/Rp = 4 × (1/5) = 4/5 ⇒ Rp = 5/4 = 1.25 Ω.'},
      'Forgetting to convert minutes to seconds when using Joule\'s heating formula H = I²Rt.'),
    createChapter('sci-ch12', 12, 'Magnetic Effects of Electric Current', 'Magnetic field and field lines, field due to current-carrying straight conductor, circular loop, and solenoid, Right-Hand Thumb Rule, Fleming’s Left-Hand Rule, electric motor principle, electromagnetic induction, domestic electric circuits.', 'jesc1', 12, 22, 28, 'not_started', 0,
      ['Properties of magnetic field lines: emerge from North, enter South; never intersect each other', 'Right-Hand Thumb Rule gives direction of magnetic field around straight wire', 'Solenoid field resembles a bar magnet', 'Fleming\'s Left-Hand Rule: Thumb (Force), Forefinger (Field), Middle (Current)'],
      [{t: 'Field Lines Rule', d: 'Never intersect because at point of intersection compass would show two directions'}, {t: 'Fleming\'s Left-Hand Rule', d: 'FBI = Force (Thumb), Magnetic Field (Index), Current (Middle)'}],
      'Electric generator and electromagnetic induction derivations have been streamlined in 2026; focus heavily on field line properties, solenoid, and domestic circuit safety (fuse, earth wire).',
      {q: 'Why does a compass needle get deflected when brought near a bar magnet or current-carrying wire?', a: 'Because a current-carrying wire produces a magnetic field that exerts a mechanical torque on the magnetic dipole of the compass needle.'},
      'Confusing Fleming\'s Left-Hand Rule (Motors/Force) with Right-Hand Thumb Rule (Field direction).'),
    createChapter('sci-ch13', 13, 'Our Environment', 'Ecosystem and its components (biotic and abiotic), food chains and food webs, 10% law of energy transfer, biological magnification, ozone depletion (CFCs), waste management and biodegradable vs non-biodegradable substances.', 'jesc1', 13, 16, 20, 'not_started', 0,
      ['10% Law of Energy: Only 10% energy transfers to next trophic level; 90% lost as heat and life processes', 'Biological Magnification: Progressive accumulation of non-biodegradable chemicals at successive trophic levels (maximum in top consumer)', 'Ozone layer (O3) depletion by CFCs and protection from UV radiation', 'Waste disposal methods: recycling, composting, biogas production'],
      [{t: '10% Law (Lindeman)', d: 'Energy decreases exponentially up the food chain; food chains rarely exceed 4-5 trophic levels'}, {t: 'Ozone Formation', d: 'O2 (UV) → O + O; O + O2 → O3'}],
      'Top carnivores or humans always have the highest concentration of toxic chemicals due to biomagnification.',
      {q: 'If 20,000 J of energy is available to plants, how much energy will be available to tigers in the food chain: Plant → Deer → Tiger?', a: 'Deer gets 10% of 20,000 J = 2,000 J. Tiger gets 10% of 2,000 J = 200 J.'},
      'Showing energy flow as cyclic; energy flow in an ecosystem is strictly UNIDIRECTIONAL.')
  ];

  const socialChapters = [
    // History
    createChapter('soc-ch1', 1, 'The Rise of Nationalism in Europe', 'Frederic Sorrieu utopian vision, French Revolution and ideas of nation, Napoleonic Code 1804, Liberal Nationalism, Zollverein, Unification of Germany (Bismarck) and Italy (Mazzini, Garibaldi, Cavour), Balkan nationalism crisis.', 'jess1', 1, 28, 35, 'completed', 100,
      ['Napoleonic Civil Code 1804 (Equality before law, secured property rights)', 'Treaty of Vienna 1815 and Conservative order', 'Unification of Germany (Otto von Bismarck) and Italy (Cavour & Garibaldi)'],
      [{t: 'Zollverein (1834)', d: 'Customs union abolishing tariff barriers and reducing currencies from 30 to 2'}, {t: 'Allegories', d: 'Marianne (France) and Germania (Germany)'}],
      'Understand the specific roles of Mazzini, Cavour, and Garibaldi in Italian unification.',
      {q: 'Explain any three features of the Napoleonic Code of 1804.', a: '1. Established equality before law. 2. Abolished privileges based on birth. 3. Secured the right to property and simplified administrative divisions.'},
      'Confusing the unification years of Germany (1871) and Italy (1861).'),
    createChapter('soc-ch2', 2, 'Nationalism in India', 'First World War impact, Satyagraha concept (Champaran, Kheda, Ahmedabad), Rowlatt Act, Jallianwala Bagh massacre (1919), Non-Cooperation Movement, Salt March, Civil Disobedience Movement, Sense of collective belonging.', 'jess1', 2, 26, 35, 'completed', 100,
      ['Satyagraha philosophy of Mahatma Gandhi', 'Non-Cooperation Movement (1920-1922) and Chauri Chaura withdrawal', 'Civil Disobedience Movement (1930) and Dandi Salt March', 'Poona Pact 1932 between Gandhi and Dr. B.R. Ambedkar'],
      [{t: 'Rowlatt Act 1919', d: 'Allowed detention of political prisoners without trial for up to 2 years'}, {t: 'Gandhi-Irwin Pact 1931', d: 'Congress agreed to join 2nd Round Table Conference in London'}],
      'Map work on Congress sessions (Calcutta, Nagpur, Madras) and Satyagraha centres carries compulsory marks.',
      {q: 'Why did Mahatma Gandhi decide to withdraw the Non-Cooperation Movement in 1922?', a: 'Due to the violent incident at Chauri Chaura (UP) where protestors burnt a police station killing 22 policemen.'},
      'Confusing the dates of Non-Cooperation Movement (1920) and Civil Disobedience Movement (1930).'),
    createChapter('soc-ch3', 3, 'The Making of a Global World', 'Pre-modern world, Silk routes, Conquest, disease and trade, Spanish conquest of Americas (Smallpox), 19th-century indenture labour, Great Depression of 1929, Bretton Woods institutions (IMF & World Bank).', 'jess1', 3, 20, 25, 'completed', 100,
      ['Silk routes connecting Asia with Europe and northern Africa', 'Smallpox biological weapon aiding Spanish conquest', 'Great Depression 1929 causes and impact on agricultural countries', 'Bretton Woods twins: IMF and World Bank'],
      [{t: 'Bretton Woods System', d: 'Post-WWII economic framework based on fixed exchange rates pegged to US dollar'}, {t: 'G-77', d: 'Coalition of developing nations demanding New International Economic Order (NIEO)'}],
      'Note: For CBSE 2026 board exam, only Section 1 (Subtopics 1 to 1.3: Pre-modern world to Conquest, disease, and trade) is evaluated in boards.',
      {q: 'Explain how smallpox acted as a deadly weapon for Spanish colonisers in America.', a: 'Native Americans had no immunity against European smallpox. It spread ahead of troops and decimated entire communities without firing a shot.'},
      'Writing about industrial revolution details when question asks specifically about pre-modern trade.'),
    createChapter('soc-ch4', 4, 'The Age of Industrialisation', 'Before Industrial Revolution (proto-industrialisation), coming up of factories, pace of industrial change, life of workers, industrialisation in colonies, market for goods.', 'jess1', 4, 22, 28, 'in_progress', 50,
      ['Proto-industrialisation: production controlled by merchants before factories emerged', 'Steam power vs hand labour in Victorian Britain', 'Early Indian entrepreneurs: Dwarkanath Tagore, Dinshaw Petit, Jamsetjee Nusserwanjee Tata'],
      [{t: 'Proto-industrialisation', d: 'Phase of industrialisation not based on factories but on rural household production'}],
      'This chapter is primarily for periodic tests in some schools but conceptual questions on Indian industrialists appear often.',
      {q: 'Why did industrialists in Victorian Britain prefer hand labour over machines?', a: 'Labor was abundant and cheap; seasonal industries needed workers only for specific months; intricate designs required handcrafting.'},
      'Assuming all production moved to machines immediately; hand labour dominated for decades.'),
    createChapter('soc-ch5', 5, 'Print Culture and the Modern World', 'First printed books in China, Japan and Korea, Gutenberg printing press, Print revolution and impact on religion (Martin Luther), French Revolution and reading mania, 19th-century women and children readers, Print in India.', 'jess1', 5, 24, 30, 'in_progress', 30,
      ['Gutenberg Bible (1448) first printed book with moveable type', 'Martin Luther Ninety-Five Theses and Protestant Reformation', 'Vernacular Press Act 1878 modelled on Irish Press Laws to censor Indian nationalist press'],
      [{t: 'Gutenberg Press', d: 'Invented in Strasbourg, Germany in 1430s using lead alloy movable metal types'}, {t: 'Vernacular Press Act (1878)', d: 'Gave British government extensive rights to censor reports and seize vernacular presses'}],
      'Understand Martin Luther’s quote: "Printing is the ultimate gift of God and the greatest one."',
      {q: 'What was the Vernacular Press Act of 1878? Why was it passed?', a: 'Passed by Lord Lytton to clamp down on vernacular nationalist newspapers that were critical of British colonial policies.'},
      'Confusing the Gutenberg press (15th century) with Chinese woodblock printing (ancient).'),

    // Geography
    createChapter('soc-ch6', 6, 'Resources and Development', 'Types of resources, sustainable development, Rio de Janeiro Earth Summit 1992, Agenda 21, Resource planning in India, Land resources, Soil types of India (Alluvial, Black, Red & Yellow, Laterite, Arid, Forest) and soil conservation.', 'jess2', 1, 16, 25, 'completed', 100,
      ['Classification of resources on basis of origin, exhaustibility, ownership, and status of development', 'Agenda 21 and Rio Earth Summit 1992 principles', 'Soil distribution: Alluvial (most fertile), Black/Regur (cotton), Laterite (tea/coffee)'],
      [{t: 'Sustainable Development', d: 'Development without damaging environment and without compromising future generation needs'}, {t: 'Black Soil', d: 'Ideal for cotton cultivation, rich in calcium carbonate and magnesium'}],
      'Map work identifying Black soil, Alluvial soil, and Laterite soil locations is guaranteed in board exams.',
      {q: 'Explain the three stages of resource planning in India.', a: '1. Identification and inventory of resources through surveying and mapping. 2. Evolving a planning structure with appropriate technology and skills. 3. Matching resource development plans with national development plans.'},
      'Marking Black soil in Northern plains instead of Deccan Trap region.'),
    createChapter('soc-ch7', 7, 'Forest and Wildlife Resources', 'Flora and fauna in India, IUCN classification of species (Normal, Endangered, Vulnerable, Rare, Endemic, Extinct), Conservation of forest and wildlife, Project Tiger 1973, Types of forests (Reserved, Protected, Unclassed), Joint Forest Management (JFM).', 'jess2', 2, 14, 20, 'completed', 100,
      ['IUCN red list categories with examples', 'Project Tiger launched in 1973 to save Bengal tigers', 'Reserved forests (most valuable for timber), Protected forests, Unclassed forests', 'Bishnoi community and Sacred Groves ecological movements'],
      [{t: 'Reserved Forests', d: 'Regarded as most valuable as far as conservation of forest and wildlife resources is concerned (>50% of total forest)'}, {t: 'Joint Forest Management', d: 'Institutional framework involving local village communities in management of degraded forests (pioneered in Odisha 1988)'}],
      'Remember that Reserved and Protected forests are also called permanent forest estates.',
      {q: 'Differentiate between Reserved and Protected forests.', a: 'Reserved forests are completely protected and commercial exploitation is banned unless granted permission (>50% of forest land). Protected forests are protected from further depletion (one-third of forest land).'},
      'Confusing endemic species (restricted to specific areas like Andaman teal) with extinct species.'),
    createChapter('soc-ch8', 8, 'Water Resources', 'Water scarcity and need for conservation, Multi-purpose river projects and integrated water resources management, Advantages and criticisms of dams (Narmada Bachao Andolan), Rainwater harvesting techniques (Guls/Kuls, Khadins, Johads, Rooftop rainwater harvesting).', 'jess2', 3, 16, 22, 'not_started', 0,
      ['Causes of water scarcity (growing population, over-exploitation, industrial pollution)', 'Jawaharlal Nehru called multi-purpose dams "Temples of modern India"', 'Rainwater harvesting in Rajasthan (Tankas) and Tamil Nadu (compulsory rooftop harvesting)'],
      [{t: 'Rainwater Harvesting', d: 'Technique of collecting and storing rainwater for domestic and agricultural use'}],
      'Remember that Tamil Nadu is the first and only state in India that made rooftop rainwater harvesting compulsory for all houses by law.',
      {q: 'Why are multi-purpose river valley projects called the "Temples of modern India"?', a: 'Because they integrate agricultural development with rapid industrialisation and economic growth of village and urban economy alike.'},
      'Listing only dams as water harvesting; rooftop harvesting and percolation pits are key.'),
    createChapter('soc-ch9', 9, 'Agriculture', 'Types of farming: Primitive subsistence, Intensive subsistence, Commercial farming, Cropping seasons (Rabi, Kharif, Zaid), Major crops (Rice, Wheat, Millets, Pulses, Sugarcane, Tea, Coffee, Cotton, Jute), Technological and institutional reforms (Bhoodan-Gramdan).', 'jess2', 4, 18, 25, 'not_started', 0,
      ['Cropping seasons: Kharif (monsoon, Rice/Maize), Rabi (winter, Wheat/Gram), Zaid (summer, Watermelon/Cucumber)', 'Geographical conditions required for Rice (hot, humid, >100 cm rain) vs Wheat (cool growing, bright sunshine, 50-75 cm rain)', 'Bhoodan-Gramdan movement led by Vinoba Bhave ("Blood-less Revolution")'],
      [{t: 'Kharif Season', d: 'Sown with monsoon onset (June-July), harvested in Sept-Oct (Rice, Cotton, Jute)'}, {t: 'Rabi Season', d: 'Sown in winter (Oct-Dec), harvested in summer (April-June) (Wheat, Barley, Mustard)'}],
      'CBSE map questions: Major Rice producing states (WB, UP, Punjab) and Major Wheat producing states (UP, Punjab, MP).',
      {q: 'State the geographical conditions required for the growth of rice in India.', a: 'High temperature (above 25°C), high humidity, annual rainfall above 100 cm. In areas of less rainfall, it grows with irrigation.'},
      'Classifying wheat as Kharif; wheat is strictly a Rabi (winter) crop.'),
    createChapter('soc-ch10', 10, 'Minerals and Energy Resources', 'What is a mineral, Mode of occurrence of minerals (Igneous, Metamorphic, Sedimentary, Placer deposits), Ferrous minerals (Iron ore, Manganese), Non-ferrous (Copper, Bauxite), Non-metallic (Mica, Limestone), Energy resources (Conventional: Coal, Petroleum, Natural gas vs Non-conventional: Solar, Wind, Biogas, Nuclear).', 'jess2', 5, 20, 28, 'not_started', 0,
      ['Four major iron ore belts in India: Odisha-Jharkhand, Durg-Bastar-Chandrapur, Ballari-Chitradurga, Maharashtra-Goa', 'Coal varieties: Anthracite (highest quality), Bituminous (most popular), Lignite (brown coal), Peat', 'Non-conventional energy sources importance for sustainable energy future'],
      [{t: 'Anthracite', d: 'Highest quality hard coal with over 80% carbon content'}, {t: 'Kudremukh', d: '100% export-oriented iron ore deposit in Karnataka (transported as slurry via pipeline)'}],
      'Map identification: Nuclear power plants (Narora, Rawatbhata, Kakrapar, Tarapur, Kalpakkam) and Thermal plants (Namrup, Singrauli, Ramagundam).',
      {q: 'Why is conservation of mineral resources necessary? State two measures.', a: 'Minerals are non-renewable, finite, and take millions of years to form. Measures: recycling of metals, using improved technology, and using renewable substitutes.'},
      'Confusing iron ore varieties (Magnetite, Hematite) with coal varieties (Anthracite, Bituminous).'),
    createChapter('soc-ch11', 11, 'Manufacturing Industries', 'Importance of manufacturing, contribution to national economy, Industrial location factors, Classification of industries (Agro-based: Textile, Sugar vs Mineral-based: Iron and steel, Aluminium smelting, Chemical, Fertilizer, Cement, Automobile, IT), Industrial pollution and environmental degradation (NTPC proactive approach).', 'jess2', 6, 22, 30, 'not_started', 0,
      ['Manufacturing is considered the backbone of economic development', 'Classification based on raw materials, capital investment, ownership, and bulk/weight', 'Information Technology and electronics industry (Bengaluru as electronic capital)', 'Measures to control environmental pollution: effluent treatment, rainwater harvesting, electrostatic precipitators'],
      [{t: 'Basic / Key Industries', d: 'Supply their products as raw materials to other industries (e.g. Iron and Steel)'}, {t: 'NTPC ISO 14001', d: 'Corporation’s proactive approach to ecological preservation and green belts'}],
      'Map work: Software Technology Parks (Noida, Gandhinagar, Mumbai, Pune, Hyderabad, Bengaluru, Chennai, Thiruvananthapuram).',
      {q: 'Why is the electronics industry very important for the Indian economy?', a: 'Provides huge employment, fosters high technological innovation, generates significant export earnings, and revolutionised communications.'},
      'Omitting waste treatment phases when asked how industrial pollution can be mitigated.'),
    createChapter('soc-ch12', 12, 'Lifelines of National Economy', 'Transport systems in India: Roadways (Golden Quadrilateral, National Highways), Railways, Pipelines, Waterways (National Waterways), Major sea ports (Kandla, Mumbai, Marmagao, New Mangalore, Kochi, Tuticorin, Chennai, Visakhapatnam, Paradip, Haldia), Airways, Communication networks, International trade and tourism.', 'jess2', 7, 18, 25, 'not_started', 0,
      ['Golden Quadrilateral Super Highways connecting Delhi-Mumbai-Chennai-Kolkata', 'Advantages of roadways over railways in hilly/rugged terrain', 'Major sea ports: Kandla (tidal port / Deendayal), Mumbai (largest natural harbour), Visakhapatnam (deepest landlocked)', 'Tourism as a trade generating employment and foreign exchange'],
      [{t: 'Golden Quadrilateral', d: '6-lane super highway project implemented by NHAI to connect four mega cities'}, {t: 'Balance of Trade', d: 'Difference between value of exports and imports (Favourable when Exports > Imports)'}],
      'Map items: Major sea ports and International airports (Amritsar, Delhi, Mumbai, Chennai, Kolkata, Hyderabad).',
      {q: 'Why are roadways considered more convenient than railways in India?', a: 'Construction cost is much lower; can negotiate higher gradients and hills; provides door-to-door service reducing loading/unloading costs.'},
      'Confusing favourable balance of trade (Exports > Imports) with unfavourable balance of trade.'),

    // Civics / Political Science
    createChapter('soc-ch13', 13, 'Power Sharing', 'Case studies of Belgium and Sri Lanka, Majoritarianism in Sri Lanka (1956 Sinhala Act), Accommodation in Belgium (Equal representation, Community government), Why power sharing is desirable (Prudential vs Moral reasons), Forms of power sharing (Horizontal, Vertical, Social groups, Political parties).', 'jess3', 1, 16, 22, 'completed', 100,
      ['Ethnic composition: Belgium (59% Dutch, 40% French) vs Sri Lanka (74% Sinhala, 18% Tamil)', 'Majoritarian policies in Sri Lanka leading to civil war', 'Belgian model: equal ministers in central govt, community govt for linguistic issues', 'Horizontal division of power (checks and balances) vs Vertical division (federalism)'],
      [{t: 'Horizontal Power Sharing', d: 'Power shared among different organs of government at same level (Legislature, Executive, Judiciary)'}, {t: 'Vertical Power Sharing', d: 'Power shared among governments at different levels (Central, State, Local)'}],
      'Prudential reason = prevents conflict and instability; Moral reason = power sharing is the very spirit of democracy.',
      {q: 'Explain the difference between horizontal and vertical power sharing.', a: 'Horizontal divides power among organs at the same level (Legislature, Executive, Judiciary) with checks and balances. Vertical divides power among levels (Union, State, Local).'},
      'Stating that Belgium suffered civil war; Belgium successfully avoided civil war through accommodation.'),
    createChapter('soc-ch14', 14, 'Federalism', 'What is Federalism? Key features of federalism, "Coming together" vs "Holding together" federations, What makes India a federal country? (Union, State, and Concurrent Lists), How is federalism practised? (Linguistic states, Language policy, Centre-State relations), Decentralisation in India (73rd and 74th Constitutional Amendments 1992).', 'jess3', 2, 18, 25, 'completed', 100,
      ['Key features of federal government (two or more levels, separate jurisdictions guaranteed by constitution)', 'Holding together federations (India, Spain, Belgium) vs Coming together (USA, Switzerland, Australia)', 'Three-fold legislative distribution: Union List, State List, Concurrent List, Residuary subjects', '1992 Decentralisation Amendment: mandatory local elections, 33% reservation for women, State Election Commission'],
      [{t: 'Union List', d: 'National importance subjects: Defence, Foreign Affairs, Banking, Currency (Centre only)'}, {t: 'Concurrent List', d: 'Shared subjects: Education, Forest, Trade Unions (Centre prevails in conflict)'}, {t: 'Residuary Subjects', d: 'Subjects not in any list (e.g. Computer Software) handled by Union Government'}],
      'Remember that India has no National Language; Hindi is declared an Official Language alongside English and 21 other scheduled languages.',
      {q: 'What major steps were taken towards decentralisation in India in 1992?', a: '1. Mandatory regular elections for local government bodies. 2. Seats reserved for SC/ST and at least one-third for women. 3. Creation of independent State Election Commission in each state.'},
      'Saying Hindi is the national language of India; Indian Constitution does not grant national language status to any language.'),
    createChapter('soc-ch15', 15, 'Gender, Religion and Caste', 'Gender and politics (Public/Private division, Feminist movements, Women political representation), Religion, communalism and politics (Communalism definitions, Secular state features in India), Caste and politics (Caste inequalities, Caste in politics vs Politics in caste).', 'jess3', 3, 16, 22, 'not_started', 0,
      ['Feminist movements demanding equality in personal and public life', 'Secular State constitutional provisions in India (Articles 14, 15, 25-28)', 'Communalism: belief that religion is the principal basis of social and political identity', 'Universal Adult Franchise and one-person-one-vote breaking traditional caste hierarchies'],
      [{t: 'Secular State', d: 'No official state religion; freedom to practice and propagate any religion; no discrimination on religious grounds'}, {t: 'Feminist', d: 'A woman or a man who believes in equal rights and opportunities for women and men'}],
      'Caste alone cannot determine elections in India: no single constituency has a clear majority of one single caste.',
      {q: 'Mention any three constitutional provisions that make India a secular state.', a: '1. No official religion for the Indian state. 2. Freedom to profess, practice, and propagate any religion. 3. Prohibits discrimination on grounds of religion.'},
      'Equating religion in politics with communalism; religion can promote ethical values, but communalism promotes intolerance.'),
    createChapter('soc-ch16', 16, 'Political Parties', 'Why do we need political parties? Functions of political parties, How many parties should we have? (One-party, Two-party, Multi-party system), National Parties criteria (BJP, INC, AAP, BSP, CPI-M, NPEP) vs State Parties, Challenges to political parties (Lack of internal democracy, Dynastic succession, Money and muscle power, Lack of meaningful choice), How can parties be reformed? (Anti-defection law, affidavit requirements, election funding).', 'jess3', 4, 20, 26, 'not_started', 0,
      ['Three components of political party: Leaders, Active members, Followers', 'Functions: contest elections, put forward policies, form and run government, play role of opposition', 'National Party criteria: 6% votes in Lok Sabha or 4 states + 4 Lok Sabha seats', 'Anti-defection law (52nd Amendment) disqualifying MPs/MLAs who change parties after winning'],
      [{t: 'National Party Criteria', d: '6% of total votes in Lok Sabha or Assembly elections in 4 states AND at least 4 Lok Sabha seats'}, {t: 'Defection', d: 'Changing party allegiance from the party on which a person got elected to a different party'}],
      'Remember that Aam Aadmi Party (AAP) is now officially recognised as a National Party by ECI.',
      {q: 'State any three challenges faced by political parties in India today.', a: '1. Lack of internal democracy and regular organisational elections. 2. Dynastic succession concentrating power in family hands. 3. Growing role of money and muscle power during elections.'},
      'Thinking regional parties only operate in one state; parties like AAP or JMM operate across multiple states.'),
    createChapter('soc-ch17', 17, 'Outcomes of Democracy', 'How do we assess democracy’s outcomes? Accountable, responsive and legitimate government, Economic growth and development, Reduction of inequality and poverty, Accommodation of social diversity, Dignity and freedom of citizens.', 'jess3', 5, 14, 20, 'not_started', 0,
      ['Democracy produces an accountable, responsive, and legitimate government', 'Democracy may be slow in decision-making, but decisions are more acceptable and effective due to deliberation', 'Democracy accommodates social diversity and resolves conflicts through peaceful dialogue', 'Democracy stands much superior to any other form of government in promoting individual dignity and freedom'],
      [{t: 'Legitimate Government', d: 'A government elected by the people through free and fair elections, ruling by established laws'}, {t: 'Transparency', d: 'Right and means of citizens to examine the process of decision making'}],
      'Democracy is not a guarantee of economic development, but ensures individual freedom and legitimacy.',
      {q: 'Why is democratic government regarded as a legitimate government?', a: 'Because it is people’s own government, elected through regular, free and fair elections where rulers are accountable to the electorate.'},
      'Saying democracies always have higher economic growth than dictatorships; historically economic growth is similar.'),

    // Economics
    createChapter('soc-ch18', 18, 'Development', 'What Development Promises – Different people, different goals, Income and other goals (freedom, security, respect), National development, How to compare different countries? (Per capita income, World Bank criterion), Public facilities, Human Development Index (HDI) by UNDP (Life expectancy, Gross enrolment, Per Capita Income).', 'jess4', 1, 16, 22, 'completed', 100,
      ['Different persons can have different developmental goals and what may be development for one may be destructive for another', 'World Bank criterion: Per Capita Income (Total National Income / Total Population)', 'UNDP criterion: HDI based on educational levels, health status (life expectancy), and per capita income', 'Public facilities like PDS, schools, and sanitation are essential because money cannot buy pollution-free environment'],
      [{t: 'Per Capita Income', d: 'Total Income of country divided by its total population (Average Income)'}, {t: 'Infant Mortality Rate (IMR)', d: 'Number of children that die before age of 1 year per 1000 live births in that year'}, {t: 'HDI Indicators', d: 'Health (Life expectancy), Education (Mean years of schooling), Standard of living (GNI per capita)'}],
      'World Bank uses ONLY Per Capita Income, whereas UNDP uses a multi-dimensional approach (HDI).',
      {q: 'Why is per capita income not an adequate indicator of human development?', a: 'Because it hides income distribution, ignores health status, life expectancy, educational attainment, clean environment, and personal security.'},
      'Confusing Infant Mortality Rate with Literacy Rate definitions.'),
    createChapter('soc-ch19', 19, 'Sectors of the Indian Economy', 'Sectors of economic activities: Primary (agriculture, fishing, mining), Secondary (manufacturing, construction), Tertiary (services, banking, IT), Historical changes in sectors, Rising importance of Tertiary sector in India, Employment generation and Disguised unemployment, Division of sectors as Organised and Unorganised, Public and Private sectors, MGNREGA 2005.', 'jess4', 2, 20, 26, 'completed', 100,
      ['Primary = direct use of natural resources; Secondary = manufacturing; Tertiary = support services', 'Tertiary sector is the largest contributor to Indian GDP, but Primary sector still employs the largest workforce', 'Disguised unemployment: more people working than required, marginal productivity is zero', 'MGNREGA 2005 guarantees 100 days of wage employment per year to rural households'],
      [{t: 'Gross Domestic Product (GDP)', d: 'Value of all final goods and services produced within a country during a particular year'}, {t: 'Disguised Unemployment', d: 'Situation where people appear employed but their removal does not reduce total output'}, {t: 'MGNREGA 2005', d: 'Right to Work: 100 days guaranteed employment or unemployment allowance'}],
      'Count ONLY final goods in GDP calculation to avoid the error of double counting intermediate goods.',
      {q: 'Why is the tertiary sector gaining immense importance in India?', a: '1. Basic services requirement (hospitals, schools, banking). 2. Growth of agriculture and industry generates demand for transport and storage. 3. Rise in income levels increases demand for tourism, shopping, and IT services.'},
      'Counting intermediate goods in GDP calculations (e.g. counting both wheat and flour and bread).'),
    createChapter('soc-ch20', 20, 'Money and Credit', 'Money as a medium of exchange, Barter system and double coincidence of wants, Modern forms of money (Currency notes, coins, Demand deposits in banks), Cheques, Loan activities of banks, Terms of credit (Collateral, Interest rate, Documentation, Mode of repayment), Formal credit (Banks and Cooperatives supervised by RBI) vs Informal credit (Moneylenders, traders, relatives), Self-Help Groups (SHGs) for the poor.', 'jess4', 3, 18, 25, 'not_started', 0,
      ['Double coincidence of wants eliminated by money as universal medium of exchange', 'Demand deposits: deposits in bank accounts that can be withdrawn on demand', 'Terms of credit: collateral, interest rate, documentation, repayment mode', 'RBI supervises formal sector loans ensuring banks lend to small farmers and entrepreneurs, not just profit businesses', 'Self-Help Groups (SHGs): typically 15-20 rural women pooling savings to provide collateral-free microloans'],
      [{t: 'Collateral', d: 'An asset that the borrower owns (land, building, vehicle, deposits) used as a guarantee to a lender until the loan is repaid'}, {t: 'Formal vs Informal Credit', d: 'Formal: RBI supervised, low interest. Informal: Unsupervised, exploitative high interest rates'}],
      'Remember that the Reserve Bank of India (RBI) issues currency notes on behalf of the central government and monitors formal bank lending.',
      {q: 'Why is cheap and affordable credit crucial for the country’s development?', a: 'It enables small farmers to invest in crops, entrepreneurs to set up industries, increases household income, and prevents vulnerable borrowers from falling into debt traps.'},
      'Thinking informal loans are safer because they require no paperwork; informal loans often result in severe debt traps.'),
    createChapter('soc-ch21', 21, 'Globalisation and the Indian Economy', 'Production across countries (Multinational Corporations - MNCs), Interlinking production across countries, Foreign trade and integration of markets, What is Globalisation? Factors enabling globalisation (Technology in telecommunications and transport, Liberalisation of foreign trade and investment), World Trade Organization (WTO), Impact of globalisation in India, Struggle for a Fair Globalisation.', 'jess4', 4, 18, 24, 'not_started', 0,
      ['MNCs set up production where costs are cheap (close to markets, skilled/unskilled labor available)', 'Liberalisation 1991: removing trade barriers and restrictions on foreign investment', 'WTO aims to liberalise international trade, but faces criticism for unequal subsidies', 'Impact: benefited consumers and large MNCs, but small domestic producers face stiff competition'],
      [{t: 'Globalisation', d: 'Process of rapid integration or interconnection between countries through trade, foreign investment, and technology'}, {t: 'Trade Barrier', d: 'Restrictions such as tax on imports (tariffs) used by governments to regulate foreign trade'}],
      'Understand how Chinese toys in India illustrate market integration: lower prices for consumers, but hurt local toy manufacturers.',
      {q: 'Explain the role of Information and Communication Technology (ICT) in promoting globalisation.', a: 'Facilitates instantaneous global communication (internet, email), teleconferencing, e-banking, and outsourcing of services like customer support at minimal cost.'},
      'Confusing liberalisation (removing barriers) with privatisation (selling public assets).'),
    createChapter('soc-ch22', 22, 'Consumer Rights', 'The consumer in the marketplace, Consumer movement in India, Consumer Protection Act (COPRA 1986 / amended 2019), Consumer rights: Right to safety, Right to be informed, Right to choose, Right to be heard, Right to seek redressal, Right to consumer education, Three-tier consumer dispute redressal machinery (District, State, National commissions), Consumer awareness (Jago Grahak Jago).', 'jess4', 5, 16, 20, 'not_started', 0,
      ['Consumer exploitation forms: adulteration, false claims, underweight goods', 'COPRA 1986 established quasi-judicial three-tier consumer courts (District, State, National)', 'Consumer rights: Right to Information, Safety, Redressal, and Choice', 'Standardisation marks: ISI mark (industrial goods), AGMARK (agricultural products), HallMark (gold jewelry)'],
      [{t: 'COPRA 1986/2019', d: 'Consumer Protection Act establishing special consumer courts for prompt, simple redressal of consumer disputes'}, {t: 'Right to Information', d: 'Consumers have the right to be informed about quality, quantity, potency, purity, standard, and price of goods'}],
      'Consumer rights chapter is often assigned as an annual project, but definitions of standard marks (ISI, AGMARK) frequently appear in MCQs.',
      {q: 'Mention any three rights of consumers guaranteed under COPRA.', a: '1. Right to Safety against hazardous goods. 2. Right to Information regarding ingredients, price, and expiry. 3. Right to Redressal against unfair trade practices.'},
      'Confusing AGMARK (food/agricultural) with ISI mark (electrical/industrial appliances).')
  ];

  const englishChapters = [
    createChapter('eng-ch1', 1, 'A Letter to God', 'Lencho\'s unflinching faith in God, devastation of cornfield by hailstorm, letter demanding 100 pesos, postmaster\'s compassion and benevolence, ironic conclusion labelling post-office employees "a bunch of crooks".', 'jeff1', 1, 12, 18, 'completed', 100,
      ['Lencho\'s pure and naive faith in divine intervention', 'Postmaster\'s altruistic gesture collecting 70 pesos to preserve faith', 'Situational irony: calling helpers "a bunch of crooks"'],
      [{t: 'Theme', d: 'Absolute faith can move mountains, but human prejudice blinds gratitude'}, {t: 'Irony', d: 'The post office employees who helped Lencho are accused of stealing'}],
      'Focus on character sketches of Lencho (hardworking, naive) and the Postmaster (compassionate, generous).',
      {q: 'Why was Lencho angry when he received the letter?', a: 'Because he found only 70 pesos instead of the 100 pesos he requested, and believed the post office employees had stolen the rest.'},
      'Saying God sent the 70 pesos; it was the postmaster and his colleagues who contributed.'),
    createChapter('eng-ch2', 2, 'Nelson Mandela: Long Walk to Freedom', 'Inauguration of South Africa’s first democratic non-racial government at Union Buildings Pretoria, Mandela’s reflection on freedom, twin obligations, bravery as triumph over fear, and rainbow nation.', 'jeff1', 2, 16, 22, 'completed', 100,
      ['Inauguration on 10th May 1994 at amphitheatre in Pretoria', 'Mandela’s definition of courage: not absence of fear, but triumph over it', 'Twin obligations: to family and to country/community'],
      [{t: 'Apartheid', d: 'System of institutionalised racial segregation and discrimination in South Africa'}, {t: 'Twin Obligations', d: 'Obligation to family/parents and obligation to people/community/country'}],
      'Mandela quotes: "Courage is not the absence of fear, but the triumph over it." Remember the date: 10 May 1994.',
      {q: 'What "twin obligations" does Nelson Mandela mention in his speech?', a: '1. Obligation to his family, parents, wife, and children. 2. Obligation to his people, his community, and his country.'},
      'Spelling Apartheid incorrectly or misdating the inauguration year (1994).'),
    createChapter('eng-ch3', 3, 'Two Stories about Flying', 'Part I: His First Flight (Liam O\'Flaherty) – young seagull conquering fear of flying through mother’s clever fish lure. Part II: Black Aeroplane (Frederick Forsyth) – mysterious pilot guiding Dakota DS 088 safely through stormy clouds.', 'jeff1', 3, 16, 22, 'completed', 100,
      ['Young seagull overcomes terror when hunger compels him to dive for fish', 'Theme of motherly tough love and self-confidence', 'Dakota pilot encounters supernatural/miraculous black aeroplane with no lights'],
      [{t: 'His First Flight Theme', d: 'Fear of failure is conquered only through courageous action'}, {t: 'Black Aeroplane Theme', d: 'The mysterious power of hope, instinct, or divine intervention during crisis'}],
      'The mystery in Black Aeroplane remains unresolved: the radar showed no other plane flying that stormy night.',
      {q: 'Why was the young seagull afraid to fly?', a: 'His wings seemed far too weak to support his weight, and looking at the vast sea below terrified him.'},
      'Assuming the black aeroplane was identified; the control tower confirmed no other plane was in the sky.'),
    createChapter('eng-ch4', 4, 'From the Diary of Anne Frank', 'Thirteen-year-old Jewish girl Anne Frank in Amsterdam hiding, gifting diary "Kitty", reflections on paper having more patience than people, school humor with Mr. Keesing and essays on chatterboxes.', 'jeff1', 4, 14, 20, 'completed', 100,
      ['"Paper has more patience than people" – reason for keeping diary', 'Anne names her diary "Kitty" as her dearest intimate confidante', 'Humorous banter with math teacher Mr. Keesing writing essays on Chatterboxes'],
      [{t: 'Key Quote', d: '"Paper has more patience than people"'}, {t: 'Essay Topics', d: 'A Chatterbox, An Incorrigible Chatterbox, Quack, Quack, Quack, Said Mistress Chatterbox'}],
      'Contrast Anne’s warm external persona with her internal longing for a true, deep friendship.',
      {q: 'Why did Anne Frank decide to write a diary?', a: 'Because she felt that she had no true friend with whom she could share her innermost feelings, and believed paper has more patience than people.'},
      'Saying Anne had no friends or family; she had loving parents and friends, but lacked a truly intimate confidante.'),
    createChapter('eng-ch5', 5, 'Glimpses of India', 'Three travelogues: I. A Baker from Goa (Lucio Rodrigues) – traditional Pader, musical bamboo, bol and kabai. II. Coorg (Lokesh Abrol) – coffee country, Kodavus martial race, Brahmagiri hills. III. Tea from Assam (Arup Kumar Datta) – Rajvir and Pranjol exploring endless green tea plantations and legends.', 'jeff1', 5, 18, 25, 'not_started', 0,
      ['Goa: Traditional bakers known as Pader, morning jingle of bamboo, traditional dress Kabai', 'Coorg (Kodagu): Smallest district of Karnataka, brave Kodavu people, Arab/Kurdish descent legend', 'Assam: World’s largest tea concentration, Bodhidharma Chinese legend vs tea discovering emperor legend'],
      [{t: 'Pader (Goa)', d: 'Traditional village baker essential for weddings, feasts, and bol cakes'}, {t: 'Coorg Warriors', d: 'Kodavus are the only people in India permitted to carry firearms without a licence'}, {t: 'Tea Legend', d: 'Chinese Emperor Shennong discovering boiled tea leaves around 2737 BC'}],
      'Each part has distinct cultural highlights: Baker (Goa), Kodavus & Coffee (Coorg), Tea Gardens (Assam).',
      {q: 'What is the tradition of baking in a Goan village described in "A Baker from Goa"?', a: 'The baker (pader) was a friend, companion, and guide. Marriages were meaningless without sweet bread "bol", and mothers prepared sandwiches on daughter’s engagement.'},
      'Mixing up the Goan baker’s dress (Kabai) with the Coorg dress (Kuppia).'),
    createChapter('eng-ch6', 6, 'Mijbil the Otter', 'Gavin Maxwell’s journey with pet otter Mijbil from Tigris marshes in Iraq to Camusfearna Scotland, playful otter antics, transport in box on airliner, Londoners’ absurd guesses about otter species.', 'jeff1', 6, 16, 22, 'not_started', 0,
      ['Maxwell adopts an otter (Lutrogale perspicillata maxwelli) after his dog dies', 'Mijbil\'s obsession with water: splashing, plunging, playing with ping-pong balls', 'Londoners’ funny guesses: walrus, seal, baby bear, beaver, hippo'],
      [{t: 'Otter Species', d: 'Lutrogale perspicillata maxwelli (Maxwell\'s otter)'}, {t: 'Key Trait', d: 'Compulsive need to play with water and roll objects on belly'}],
      'Humorous narrative depicting the unique bond between human and wild animal companion.',
      {q: 'How did Mijbil pass his time in London?', a: 'By playing with marbles, rubber fruit, ping-pong balls, and inventing a game on a broken suitcase wall with a ball.'},
      'Saying Maxwell bought Mijbil in London; he received him in Basra (Iraq).'),
    createChapter('eng-ch7', 7, 'Madam Rides the Bus', 'Eight-year-old Valliammai (Valli) meticulous planning to experience bus ride from village to nearby town, saving 60 paise, observing lively world, contrasting joy with sight of dead cow.', 'jeff1', 7, 18, 24, 'not_started', 0,
      ['Valli\'s meticulous calculation: 30 paise one way, 45 minutes journey time', 'Self-respecting conduct: refusing conductor’s treat and asserting independence', 'Encounter with lively galloping cow going, and tragic dead cow on return journey teaching life/death realities'],
      [{t: 'Fare & Schedule', d: '30 paise each way (60 paise total), 1:00 PM bus returning by 2:45 PM'}, {t: 'Theme', d: 'Curiosity, innocent determination, and sudden maturity through observing mortality'}],
      'Valli’s refusal to accept a cold drink from the conductor demonstrates her strong self-respect and dignity.',
      {q: 'How did Valli plan and prepare for her bus ride?', a: 'She listened to neighbours’ conversations, asked questions, gathered fare details (60 paise), and resisted buying toys/candies to save money.'},
      'Thinking Valli was accompanied by her mother; she undertook the journey entirely alone.'),
    createChapter('eng-ch8', 8, 'The Sermon at Benares', 'Gautama Buddha’s enlightenment at Bodh Gaya, first sermon at Benares on suffering, Kisa Gotami mourning dead son, mustard seed quest revealing universal mortality of living beings.', 'jeff1', 8, 14, 20, 'not_started', 0,
      ['Prince Siddhartha leaves royal palace upon seeing sick man, old man, funeral procession, and monk', 'Attains enlightenment under Bodhi tree and preaches first sermon at Benares (holy city on Ganga)', 'Kisa Gotami learns that death is universal and grief cannot revive the deceased'],
      [{t: 'Buddha\'s Core Message', d: 'The life of mortals in this world is troubled, brief, and combined with pain; peace of mind comes only by overcoming lamentation'}, {t: 'Mustard Seed Lesson', d: 'No house is untouched by death; all mortals must die like ripe fruit or earthen vessels'}],
      'The metaphor comparing mortals to earthen vessels made by a potter that break easily.',
      {q: 'What did the Buddha ask Kisa Gotami to bring, and what condition was attached to it?', a: 'A handful of mustard seeds from a house where no one had ever lost a child, husband, parent, or friend to death.'},
      'Assuming Buddha revived the child; Buddha guided her to accept the universal truth of mortality.'),
    createChapter('eng-ch9', 9, 'The Proposal', 'Anton Chekhov one-act farce: Ivan Lomov visiting neighbour Stepan Chubukov to propose to daughter Natalya Stepanovna, erupting into petty comic squabbles over Oxen Meadows and hunting dogs (Guess vs Squeezer).', 'jeff1', 9, 20, 26, 'not_started', 0,
      ['Russian one-act satire on wealthy landowning classes entering marriages of economic convenience', 'Trivial arguments: ownership of Oxen Meadows, superiority of hunting dogs Guess vs Squeezer', 'Hypocrisy of characters who pretend affection yet cannot stop quarrelling'],
      [{t: 'Genre', d: 'Farce / Satirical Comedy of Manners'}, {t: 'Disputed Properties', d: 'Oxen Meadows (touching Birchwoods) and hunting dogs (Guess vs Squeezer)'}],
      'Understand the humor in Chubukov blessing the marriage while shouting "Bring in champagne!" as the couple resumes quarrelling.',
      {q: 'Why does Lomov wish to marry Natalya Stepanovna?', a: 'He is already 35 (critical age), suffers from palpitations, and seeks an orderly, regular life with an educated, capable housekeeper.'},
      'Taking the argument seriously; it is a farce meant to ridicule petty bourgeois landed disputes.'),
    createChapter('eng-ch10', 10, 'A Triumph of Surgery', 'Dr. James Herriot treating pampered overweight dachshund Tricki belonging to wealthy Mrs. Pumphrey, curing dog through strict diet and exercise among active pack rather than surgical medicine.', 'jeff2', 1, 14, 20, 'not_started', 0,
      ['Tricki turned into a "bloated sausage" due to Mrs. Pumphrey’s overfeeding of cream cakes and cod-liver oil', 'Dr. Herriot’s sensible treatment: no medical drugs, plenty of water, and running with dog pack', 'Mrs. Pumphrey misinterprets physical recovery as a "triumph of surgery"'],
      [{t: 'Theme', d: 'Excessive indulgence can be destructive; simple exercise and discipline restore health'}, {t: 'Irony', d: 'No actual surgery occurred, yet it is called a "Triumph of Surgery"'}],
      'Character sketch of Dr. Herriot: practical, tactful, sensible veterinarian.',
      {q: 'What was Mrs. Pumphrey’s reaction when Tricki recovered at the surgery?', a: 'Her eyes filled with tears, her lips trembled, and she declared with immense gratitude that it was a "Triumph of Surgery".'},
      'Thinking Tricki underwent medication or operation; recovery was achieved entirely via diet and exercise.'),
    createChapter('eng-ch11', 11, 'The Thief\'s Story', 'Ruskin Bond story of 15-year-old thief Hari Singh befriending generous struggling writer Anil, stealing 600 rupees, but returning conscience-stricken because education and trust are worth more than stolen cash.', 'jeff2', 2, 14, 20, 'not_started', 0,
      ['Hari Singh changes his name monthly to evade police and former employers', 'Anil teaches Hari to cook, write sentences, and add numbers', 'Hari steals cash, waits at railway platform, but conscience and desire for respect make him return the damp notes'],
      [{t: 'Theme', d: 'Unconditional trust, love, and education can reform even a hardened petty criminal'}, {t: 'Anil\'s Greatness', d: 'He knew Hari tried to steal the money, but never expressed anger or handed him to police'}],
      'The silent understanding between Anil and Hari: Anil gives him a 50-rupee note the next morning acknowledging transformation.',
      {q: 'Why did Hari Singh return to Anil after stealing the money?', a: 'Because he realised that stealing could give him temporary cash, but learning to read and write from Anil could give him dignity, respect, and a genuine career.'},
      'Saying Anil was angry; Anil remained composed and encouraged Hari to continue studying.')
  ];

  const hindiChapters = [
    createChapter('hin-ch1', 1, 'पद (सूरदास)', 'भ्रमरगीत सार से चयनित चार पद, उद्धव-गोपी संवाद, गोपियों का सगुण कृष्ण प्रेम बनाम उद्धव का निर्गुण ज्ञान मार्ग, योग संदेश को कड़वी ककड़ी बताना।', 'jhks1', 1, 12, 18, 'completed', 100,
      ['गोपियों की वाग्विदग्धता और अनन्य कृष्ण भक्ति', 'उद्धव के योग संदेश को "कड़वी ककड़ी" और "व्याधि" कहना', 'कमल के पत्ते और तेल की गागर के दृष्टांत'],
      [{t: 'सूरदास की भाषा', d: 'सरस एवं संगीतमय ब्रजभाषा'}, {t: 'भ्रमरगीत प्रसंग', d: 'उद्धव का ज्ञान मार्ग गोपियों के एकनिष्ठ प्रेम के आगे नतमस्तक हो जाता है'}],
      'गोपियों के तर्कों और उपालंभों को अच्छी तरह समझें।',
      {q: 'गोपियों ने उद्धव के योग संदेश की तुलना किससे की है?', a: 'गोपियों ने उद्धव के योग संदेश को "कड़वी ककड़ी" के समान और ऐसी "व्याधि" बताया है जिसे उन्होंने पहले कभी न देखा न सुना था।'},
      'गोपियों को अज्ञानी समझना; वे परम चतुर और वाक्पटु हैं।'),
    createChapter('hin-ch2', 2, 'राम-लक्ष्मण-परशुराम संवाद (तुलसीदास)', 'रामचरितमानस के बालकांड से संकलित, शिव धनुष टूटने पर परशुराम का क्रोध, लक्ष्मण के व्यंग्य बाण, राम का शांत और विनीत स्वभाव।', 'jhks1', 2, 16, 22, 'completed', 100,
      ['शिवधनुष भंजन के बाद परशुराम का प्रचंड क्रोध', 'लक्ष्मण का निडरतापूर्वक व्यंग्य करना ("इहाँ कुम्हड़बतिया कोउ नाहीं")', 'राम के शीतल वचनों द्वारा परशुराम के क्रोध को शांत करना'],
      [{t: 'तुलसीदास की भाषा', d: 'अवधी भाषा (दोहा और चौपाई छंद)'}, {t: 'वीर और रौद्र रस', d: 'परशुराम के संवादों में रौद्र रस और लक्ष्मण के वचनों में वीर रस तथा हास्य-व्यंग्य'}],
      'चौपाई और दोहा छंदों की संगीतात्मकता और वीर रस के अलंकारों पर ध्यान दें।',
      {q: 'लक्ष्मण ने परशुराम के क्रोध को शांत करने के लिए किन तर्कों का प्रयोग किया?', a: 'लक्ष्मण ने कहा कि बचपन में हमने अनेक धनुहियाँ तोड़ीं तब तो किसी ने क्रोध नहीं किया; यह पुराना धनुष तो छूते ही टूट गया, इसमें राम का कोई दोष नहीं है।'},
      'परशुराम को दुष्ट समझना; वे महान तपस्वी और क्रोधी स्वभाव के ब्राह्मण योद्धा थे।'),
    createChapter('hin-ch3', 3, 'आत्मकथ्य (जयशंकर प्रसाद)', 'छायावादी कवि जयशंकर प्रसाद द्वारा आत्मकथा न लिखने के कारण, जीवन की विडंबनाएं, स्मृति को पाथेय बनाना, अपनी सरलता का उपहास न उड़ाना।', 'jhks1', 3, 10, 16, 'completed', 100,
      ['आत्मकथा लिखने के मित्रों के आग्रह को विनम्रता से अस्वीकार करना', 'जीवन की खाली गागर और अभावों का भावपूर्ण चित्रण', 'प्रिया की मधुर स्मृतियों को जीवन का "पाथेय" (रास्ते का संबल) मानना'],
      [{t: 'काव्य प्रवृत्ति', d: 'छायावादी कविता, प्रतीकात्मक एवं लाक्षणिक खड़ी बोली'}, {t: 'मुख्य संदेश', d: 'कवि अपने व्यक्तिगत दुखों और अभावों को सार्वजनिक तमाशा नहीं बनाना चाहते'}],
      'प्रसाद जी के आत्मकथ्य की लाक्षणिक पदावली और रूपक अलंकारों को समझें।',
      {q: 'कवि आत्मकथा लिखने से क्यों बचना चाहते हैं?', a: 'क्योंकि कवि का जीवन दुखों और अभावों से भरा रहा है; वे अपनी व्यथा को मौन रखकर दूसरों को उपहास का अवसर नहीं देना चाहते।'},
      'कवि को अहंकारी समझना; कवि अत्यंत विनम्र और सादगीपूर्ण हैं।'),
    createChapter('hin-ch4', 4, 'उत्साह और अट नहीं रही (सूर्यकांत त्रिपाठी निराला)', 'उत्साह: बादलों को क्रांति और नवरचना का अग्रदूत मानकर गर्जन का आह्वान। अट नहीं रही: फाल्गुन मास की प्राकृतिक सुंदरता और मादक सौंदर्य का सजीव वर्णन।', 'jhks1', 4, 12, 18, 'not_started', 0,
      ['उत्साह कविता में बादलों को क्रांति चेतना और नवजीवन देने वाले कवि के रूप में प्रस्तुत करना', 'बादल को "विप्लव के वीर" और "गर्जो!" कहकर सामाजिक परिवर्तन का प्रेरक मानना', 'फाल्गुन की प्राकृतिक शोभा इतनी व्यापक है कि वह प्रकृति और हृदय में समा नहीं पा रही'],
      [{t: 'उत्साह', d: 'आह्वान गीत, ओज गुण सम्पन्न, क्रांति और नवसृजन का प्रतीक'}, {t: 'अट नहीं रही', d: 'फाल्गुन मास के प्राकृतिक सौंदर्य का चित्रात्मक वर्णन'}],
      'निराला जी के ओज गुण और प्रकृति चित्रण दोनों का सुंदर समन्वय है।',
      {q: 'कवि बादलों से बरसने के बजाय गरजने के लिए क्यों कहता है?', a: 'क्योंकि गर्जना क्रांति, उत्साह और पौरुष का प्रतीक है जो समाज में जड़ता को तोड़कर नवचेतना लाती है।'},
      'उत्साह को केवल वर्षा ऋतु का सामान्य वर्णन मानना; यह क्रांति का आह्वान गीत है।'),
    createChapter('hin-ch5', 5, 'यह दंतुरित मुसकान और फसल (नागार्जुन)', 'यह दंतुरित मुसकान: नन्हें शिशु की पहली मुस्कान में मृतक में भी जान फूंकने की शक्ति, प्रवासी पिता का वात्सल्य। फसल: कोटि-कोटि हाथों के श्रम, नदियों के पानी, मिट्टियों के गुणधर्म और धूप-हवा का थिरकन।', 'jhks1', 5, 12, 18, 'not_started', 0,
      ['शिशु की दंतुरित मुस्कान का पाषाण हृदय को भी पिघला देने वाला प्रभाव', 'अतिथि पिता और नन्हें शिशु के बीच प्रथम परिचय का भावुक क्षण', 'फसल किसी एक की नहीं, बल्कि प्रकृति और मानव श्रम के सामूहिक योगदान का परिणाम है'],
      [{t: 'वात्सल्य रस', d: 'शिशु की निष्पाप मुस्कान और पिता का वात्सल्य भाव'}, {t: 'फसल की महत्ता', d: 'प्रकृति (मिट्टी, जल, सूर्य, हवा) और मनुष्य के अथक परिश्रम का साकार रूप'}],
      'नागार्जुन जी को जनकवि कहा जाता है; उनकी भाषा अत्यंत सरल, सहज और जनवादी है।',
      {q: 'कवि ने फसल को किसके किसके श्रम और योगदान का परिणाम बताया है?', a: 'कवि के अनुसार फसल नदियों के पानी का जादू, विभिन्न मिट्टियों का गुणधर्म, सूरज की किरणों का रूपांतरण और लाखों-करोड़ों किसानों के हाथों के श्रम की गरिमा है।'},
      'फसल को केवल प्राकृतिक उपज समझना; यह मानव श्रम का परिणाम है।'),
    createChapter('hin-ch6', 6, 'संगतकार (मंगलेश डबराल)', 'मुख्य गायक के सुर में सुर मिलाने वाले संगतकार की भूमिका, उसकी आवाज में हिचक और सुर को ऊंचा न उठने देने की मर्यादा, उसकी मनुष्यता और त्याग।', 'jhks1', 6, 10, 15, 'not_started', 0,
      ['मुख्य गायक के भारी सुर को सहारा देने वाले सहायक कलाकार (संगतकार) का महत्व', 'जब मुख्य गायक का कंठ बैठता है तब संगतकार सुर को बिखरने से बचाता है', 'संगतकार की आवाज की हिचक उसकी विफलता नहीं, बल्कि मुख्य गायक के प्रति उसकी निष्ठा और "मनुष्यता" है'],
      [{t: 'मुख्य भाव', d: 'नेपथ्य में रहकर कार्य करने वाले सहायकों का अपरिहार्य योगदान'}, {t: 'मनुष्यता', d: 'स्वयं पीछे रहकर मुख्य कलाकार को प्रतिष्ठा दिलाना'}],
      'जीवन के प्रत्येक क्षेत्र (नाटक, खेल, राजनीति) में संगतकार की भूमिका को उदाहरण सहित जोड़ें।',
      {q: 'संगतकार की आवाज में जो हिचक सुनाई देती है, उसे कवि ने उसकी मनुष्यता क्यों कहा है?', a: 'क्योंकि वह स्वयं में प्रतिभा होते हुए भी मुख्य गायक के सुर को श्रेष्ठ बनाए रखने के लिए अपने सुर को दबाए रखता है; यह उसका त्याग और मर्यादा है।'},
      'संगतकार को कमजोर गायक समझना; वह मुख्य गायक का संबल है।'),
    createChapter('hin-ch7', 7, 'नेताजी का चश्मा (स्वयं प्रकाश)', 'हालदार साहब की कस्बे से यात्रा, देशभक्त कैप्टन चश्मेवाले का सुभाष चंद्र बोस की मूर्ति पर चश्मा बदलना, देश के प्रति त्याग और सम्मान की सच्ची भावना, सरकंडे का चश्मा।', 'jhks1', 7, 14, 20, 'not_started', 0,
      ['कस्बे के चौराहे पर नेताजी सुभाष चंद्र बोस की संगमरमर की मूर्ति बिना चश्मे के', 'गरीब, लंगड़ा कैप्टन चश्मेवाला नेताजी की मूर्ति पर अपने चश्मों में से एक फ्रेम लगाता है', 'पानवाले का उपहास उड़ाना लेकिन कैप्टन की मृत्यु पर भावुक होना', 'बच्चों द्वारा सरकंडे का चश्मा लगाना सिद्ध करता है कि देशभक्ति भावी पीढ़ी में जीवित है'],
      [{t: 'व्यंग्य व मर्म', d: 'शारीरिक रूप से अक्षम व्यक्ति भी सच्चे मन से राष्ट्रभक्ति निभा सकता है'}, {t: 'देशभक्ति की परिभाषा', d: 'देश सीमाओं से नहीं, बल्कि उसमें रहने वाले नागरिकों, प्रकृति और संस्कृति से बनता है'}],
      'कैप्टन कोई सेनानी नहीं था, फिर भी लोग उसे "कैप्टन" क्यों कहते थे - इस प्रश्न का अभ्यास करें।',
      {q: 'मूर्ति पर सरकंडे का चश्मा देखकर हालदार साहब भावुक क्यों हो गए?', a: 'क्योंकि उन्हें विश्वास हो गया कि देश की भावी पीढ़ी (बच्चों) के मन में भी देश के शहीदों और देशभक्तों के प्रति अपार सम्मान और निष्ठा जीवित है।'},
      'कैप्टन को आजाद हिंद फौज का सिपाही समझना; वह एक साधारण चश्मा विक्रेता था।'),
    createChapter('hin-ch8', 8, 'बालगोबिन भगत (रामवृक्ष बेनीपुरी)', 'कबीरपंथी गृहस्थ संत बालगोबिन भगत का चरित्र, आडंबरहीन जीवन, संगीत साधना, पुत्र की मृत्यु पर उत्सव मनाना, पतोहू का पुनर्विवाह कराकर समाज सुधार की मिसाल।', 'jhks1', 8, 16, 22, 'not_started', 0,
      ['बालगोबिन भगत गृहस्थ होते हुए भी मन, वाणी और कर्म से सच्चे संन्यासी थे', 'कबीर के पदों का मधुर गायन और प्रभातियों की संगीत साधना', 'इकलौते पुत्र की मृत्यु पर विलाप न करके आत्मा के परमात्मा से मिलन का उत्सव मनाना', 'विधवा पतोहू को उसके भाई के साथ भेजकर पुनर्विवाह का क्रांतिकारी कदम उठाना'],
      [{t: 'संन्यास की नई परिभाषा', d: 'संन्यास का आधार बाहरी वेशभूषा नहीं, बल्कि अंतःकरण की पवित्रता और वैराग्य है'}, {t: 'कबीर पंथ', d: 'जाति-पांति और सामाजिक रूढ़ियों का विरोध'}],
      'भगत जी के संगीत का खेतों में काम कर रहे किसानों पर प्रभाव वाला अंश अत्यंत महत्वपूर्ण है।',
      {q: 'बालगोबिन भगत की दिनचर्या लोगों के आश्चर्य का कारण क्यों थी?', a: 'क्योंकि वृद्धावस्था और कड़ाके की ठंड में भी वे भोर में दो मील दूर नदी स्नान करते, खंजड़ी बजाकर प्रभाती गाते और अपने नियमों का दृढ़ता से पालन करते थे।'},
      'भगत जी को साधु वेशधारी भिखारी समझना; वे स्वाभिमानी किसान गृहस्थ थे।'),
    createChapter('hin-ch9', 9, 'लखनवी अंदाज़ (यशपाल)', 'ट्रेन के सेकंड क्लास डिब्बे में नवाब साहब का दिखावटी जीवन, खीरा छीलना, नमक-मिर्च बुरकना और बिना खाए केवल सूंघकर खिड़की से बाहर फेंक देना, पतनशील सामंती वर्ग पर करारा व्यंग्य।', 'jhks1', 9, 14, 20, 'not_started', 0,
      ['सेकंड क्लास के एकांत डिब्बे में लेखक की नवाब साहब से अप्रत्याशित भेंट', 'नवाब साहब द्वारा खीरे को करीने से काटना, सूंघना और पेट भर जाने की डकार लेकर फेंकना', 'यह प्रदर्शनकारी बनावटी जीवनशैली पर व्यंग्य है', 'लेखक का निष्कर्ष: जब बिना खाए पेट भर सकता है तो बिना विचार और पात्र के नई कहानी भी लिखी जा सकती है'],
      [{t: 'व्यंग्य का विषय', d: 'सामंती वर्ग की खोखली प्रतिष्ठा और दिखावे की संस्कृति'}, {t: 'नई कहानी पर कटाक्ष', d: 'बिना घटना और कथ्य के कहानी लिखने वालों पर व्यंग्य'}],
      'यशपाल जी का भाषा प्रवाह और नवाब साहब के हाव-भाव का सूक्ष्म वर्णन अद्वितीय है।',
      {q: 'नवाब साहब ने खीरा खाने की तैयारी किस प्रकार की और अंत में क्या किया?', a: 'उन्होंने खीरे धोए, तौलिए से पोंछे, फांकों पर जीरा-मिला नमक और मिर्च बुरका, फिर प्रत्येक फांक को सूंघकर खिड़की से बाहर फेंक दिया और तृप्ति की डकार ली।'},
      'इस पाठ को केवल हास्य कथा समझना; यह दिखावे की प्रवृत्ति पर गंभीर सामाजिक व्यंग्य है।'),
    createChapter('hin-ch10', 10, 'एक कहानी यह भी (मन्नू भंडारी)', 'मन्नू भंडारी की आत्मकथात्मक कृति, पिता के अंतर्विरोधी व्यक्तित्व (उदार लेकिन शक्की), कॉलेज की प्राध्यापिका शीला अग्रवाल का प्रभाव, आजादी के आंदोलन में भागीदारी, स्त्री चेतना का विकास।', 'jhks1', 10, 16, 22, 'not_started', 0,
      ['लेखिका के बाल्यकाल और अजमेर के माहौल का चित्रण', 'पिता के शक्की स्वभाव और लेखिका के रंग-रूप को लेकर हीनभावना का विकास', 'कॉलेज में शीला अग्रवाल द्वारा साहित्यिक अभिरुचि और राजनीतिक चेतना जगाना', '1942 के भारत छोड़ो आंदोलन और 1946-47 के जनआंदोलनों में लेखिका का ओजस्वी नेतृत्व'],
      [{t: 'स्त्री चेतना', d: 'चारदीवारी से निकलकर स्वाधीनता और साहित्यिक सृजन में सक्रिय भागीदारी'}, {t: 'पिता-पुत्री संबंध', d: 'वैचारिक टकराव के साथ-साथ पिता के गर्व का अनुभव'}],
      'शीला अग्रवाल ने मन्नू भंडारी के जीवन को किस प्रकार नई दिशा दी, यह दीर्घ उत्तरीय प्रश्न हेतु तैयार करें।',
      {q: 'मन्नू भंडारी के जीवन में प्राध्यापिका शीला अग्रवाल का क्या योगदान था?', a: 'शीला अग्रवाल ने लेखिका की साहित्यिक रुचि का दायरा बढ़ाया, उन्हें अच्छे साहित्य से परिचित कराया और उनमें क्रांतिकारी चेतना जगाकर स्वतंत्रता आंदोलन में कूदने का हौसला दिया।'},
      'लेखिका और उनके पिता में केवल विरोध समझना; पिता अंततः उनकी सफलता और लोकप्रियता पर गर्व करते थे।')
  ];

  return [
    {
      id: 'math',
      name: 'Mathematics',
      code: 'MATH-10',
      color: '#2B6DEF',
      bgLight: '#EBF2FE',
      icon: 'fa-solid fa-calculator',
      gradient: 'linear-gradient(135deg, #2B6DEF 0%, #174BB8 100%)',
      chaptersCount: mathChapters.length,
      completedCount: mathChapters.filter(c => c.status === 'completed').length,
      chapters: mathChapters
    },
    {
      id: 'science',
      name: 'Science',
      code: 'SCI-10',
      color: '#059669',
      bgLight: '#E6F4EA',
      icon: 'fa-solid fa-flask-vial',
      gradient: 'linear-gradient(135deg, #059669 0%, #047857 100%)',
      chaptersCount: scienceChapters.length,
      completedCount: scienceChapters.filter(c => c.status === 'completed').length,
      chapters: scienceChapters
    },
    {
      id: 'social',
      name: 'Social Science',
      code: 'SST-10',
      color: '#D97706',
      bgLight: '#FEF3C7',
      icon: 'fa-solid fa-earth-americas',
      gradient: 'linear-gradient(135deg, #D97706 0%, #B45309 100%)',
      chaptersCount: socialChapters.length,
      completedCount: socialChapters.filter(c => c.status === 'completed').length,
      chapters: socialChapters
    },
    {
      id: 'english',
      name: 'English',
      code: 'ENG-10',
      color: '#7C3AED',
      bgLight: '#EDE9FE',
      icon: 'fa-solid fa-book-open-reader',
      gradient: 'linear-gradient(135deg, #7C3AED 0%, #6D28D9 100%)',
      chaptersCount: englishChapters.length,
      completedCount: englishChapters.filter(c => c.status === 'completed').length,
      chapters: englishChapters
    },
    {
      id: 'hindi',
      name: 'Hindi',
      code: 'HIN-10',
      color: '#DC2626',
      bgLight: '#FEE2E2',
      icon: 'fa-solid fa-pen-nib',
      gradient: 'linear-gradient(135deg, #DC2626 0%, #B91C1C 100%)',
      chaptersCount: hindiChapters.length,
      completedCount: hindiChapters.filter(c => c.status === 'completed').length,
      chapters: hindiChapters
    }
  ];
}

module.exports = { getClass10Subjects };
